### ISSUE TITLE
kubernetes doc

### ISSUE THREAD

**Issue by mythi** [clearlinux/clear-linux-documentation#1003]
**Describe the error/improvement to an existing document or image**

some feedback: https://github.com/clearlinux/distribution/issues/1663#issuecomment-577411817

**Comment by mvincerx** [comment]
I'll take this. Currently testing k8s and encountering other warnings and errors. See also: #894

**Comment by mvincerx** [comment]
This is a separate but related issue that we need to document: 
We can only use one runtime at a time: docker, crio, containerd
Currently, this is done by: --cri-socket=/run/crio/crio.sock
This is applicable if alternative runtimes are used.

**Comment by mvincerx** [comment]
Roll up changes here to #894
