### ISSUE TITLE
Document how to permanently enable hugepages

### ISSUE THREAD

**Issue by eadamsintel** [clearlinux/clear-linux-documentation#1005]
This is a placeholder for myself and @bktan8 to discuss where the appropriate place is to document how to enable hugepages. The [DPDK ](https://www.reddit.com/r/ClearLinux/comments/egaof2/how_to_enable_huge_pages_on_clear_linux/)page describe how to do it temporarily but for permanent use you need to do the following. This may need to be documented in any pages describing different `clr-boot-manager` options and would also make sense in any Kubernetes enabling pages. 
```
cat << EOF | sudo tee -a /etc/kernel/cmdline.d/hugepages.conf
default_hugepagesz=2M
hugepagesz=2M
hugepages=1024
EOF
sudo clr-boot-manager update
```

You can verify with `grep ^Huge /proc/meminfo`

**Comment by bktan8** [comment]
@eadamsintel - I would put a how-to in the "Maintenance" section and then add to the bottom of https://docs.01.org/clearlinux/latest/guides/maintenance/resource-limits.html as a "Related" topic.  

In addition to how to enable and verify, add a how to remove Hugepages -- all in one doc.

**Comment by eadamsintel** [comment]
I started to write this doc when I realized that Huge Pages is already enabled in Clear Linux. My issue is that the number of hugepages needs to be configured before starting a kubernetes cluster. This can be done permanently or temporarily such as `echo 1024 | sudo tee /sys/kernel/mm/hugepages/hugepages-2048kB/nr_hugepages` 

We should discuss whether a more comprehensive hugepage document is needed that goes into detail on hugepages or if just making a note in the Kubernetes documentation on how to enable before starting a cluster is adequate.

**Comment by mvincerx** [comment]
@eadamsintel, Given your discovery on adding this before launching a k8s cluster, let's integrate that config step in the work of GH-1030. I'll add the general issue as an open to discuss this in our next docs meeting. @puneetse FYI.

**Comment by eadamsintel** [comment]
I think that is the right approach. However, hugepages can be configured different ways and a node can only pre-allocate huge pages for one size which has to be done before bringing up the cluster.   Id suggest having a small section in the kubernetes doc you link to with a link to https://kubernetes.io/docs/tasks/manage-hugepages/scheduling-hugepages/ with an example command on how to verify huge pages is enabled (it should be) and the example command above on how to configure for 2MiB size.

**Comment by mvincerx** [comment]
Let's add a note to the new k8s per @eadamsintel. Please add to the FAQ too. Thanks
