### ISSUE TITLE
Incorrect (obsolete) steps to build an image

### ISSUE THREAD

**Issue by jurobystricky** [clearlinux/clear-linux-documentation#1006]
"Example 4: Build an Image" https://docs.01.org/clearlinux/latest/guides/clear/mixer.html no longer works with the JSON file. Seems mixer now uses yaml instead. Although the mixer converts the JSON file to yaml file, the image does no build due to some unresolved binaries in /usr/bin/XXX. The documentation should probably avoid all JSON references and replace them with a step-by-step example using a yaml file.

**Comment by mvincerx** [comment]
@bktan8, do you have time to review this?

**Comment by bktan8** [comment]
I'll take it.

**Comment by mvincerx** [comment]
Thanks, @bktan8
