### ISSUE TITLE
Guide clarifying clr-power-tweaks behavior

### ISSUE THREAD

**Issue by insilications** [clearlinux/clear-linux-documentation#1011]
My suggestion is that there should be some documentation about clr-power-tweaks. I had a major headache trying to use systemd to create a service to apply some settings related to swappiness and dirty_ratio and seeing that there were being constantly overridden somewhere in the boot process. After days I figured out that clr-power-tweaks is not strictly aiming at changing common power settings and adjusting them to an optimal Intel configuration, but it is also changing several other settings as well. Another suggestion would be a way to make a custom [clr-power-tweaks.cfg](https://github.com/clearlinux/clr-power-tweaks/blob/master/clr-power-tweaks.conf) and update it through a shell command (e.g. "clr-power-tweaks update"). I will open an issue about this in the main distribution channel.

Target audience: System Administrator

Format: guide/clr-power-tweaks

Example of similar documents: swupd

**Comment by mvincerx** [comment]
Will hold until clr-distro is resolved.

**Comment by mvincerx** [comment]
@krisdale and @puneetse please work together! 👍

**Comment by puneetse** [comment]
Manpage PR https://github.com/clearlinux/clr-power-tweaks/pull/16

**Comment by puneetse** [comment]
The manpage has been published. I'm going to hold on this until https://github.com/clearlinux/clear-linux-documentation/issues/801 and our discussions about getting manpages part of the doctree in general.

**Comment by mvincerx** [comment]
Dependent on manpages.

**Comment by mvincerx** [comment]
Closed per release of GH-1110. 
clr-power-tweaks manpages added, thanks to @intelkevinputnam
