### ISSUE TITLE
OpenSSH X11 instructions need to be upated

### ISSUE THREAD

**Issue by puneetse** [clearlinux/clear-linux-documentation#1027]
**Describe the error/improvement to an existing document or image**
The settings in the OpenSSH documentation to enable X11 forwarding do not include all the settings to disable the security that Clear Linux defaults to.

The details are in the `man stateless` page. 

**Additional context**
https://community.clearlinux.org/t/no-attempt-to-forward-x-over-ssh-has-succeeded/2938

**Comment by mvincerx** [comment]
@eadamsintel please check in with @bd-dean on this re `systemd`.

**Comment by mvincerx** [comment]
LGTM.
