### ISSUE TITLE
Correct documentation for swupd in bare-metal-install-server, Automatic OS Updates

### ISSUE THREAD

**Issue by mvincerx** [clearlinux/clear-linux-documentation#1038]
Correct the screenshot (Fig 32) in https://docs.01.org/clearlinux/latest/get-started/bare-metal-install-server.html, after clr-installer engineering team revises embedded URL in clr-installer [live-server]. 

**Screenshots**
[Automatic OS Updates]
![automatic-os-updates](https://user-images.githubusercontent.com/37549381/74985852-2d43e400-53ed-11ea-9b53-9e17638435f7.png)

**Comment by mvincerx** [comment]
This issue is dependent on  https://github.com/clearlinux/clr-installer/issues/667

**Comment by mvincerx** [comment]
@mvincerx Check this out!

**Comment by mdhorn** [comment]
Updated in release 2.4.1 of the clr-installer
![image](https://user-images.githubusercontent.com/12535259/75937986-55930000-5e3b-11ea-90fc-1f629e894c96.png)
