### ISSUE TITLE
Include note in DLRS documentation about installing extra components to DLRS images (swupd bundle-add)

### ISSUE THREAD

**Issue by joselamego** [clearlinux/clear-linux-documentation#1041]
Some modification procedures to the DLRS images might provoque unexpected results due to the undesired modification of the DLRS core components; for example, executing `swupd bundle-add computer-vision-basic` in a container running _stacks-tensorflow-mkl_ overwrites installed openvino components and produces undesired behavior and failures.

This request is to appropriately phrase and add a note to the DLRS documentation (README files, release notes and any other that might be relevant) stating that any modification to the DLRS images or the containers running it is at the user's responsibility due to the possible core components modification. The `swupd bundle-add` command may be a useful example.

The note should be included at latest AND past releases documentation.

**Comment by mvincerx** [comment]
Thanks, @bd-dean!

**Comment by bd-dean** [comment]
@joselamego thanks for submitting this -- I'll include you in the review!

**Comment by joselamego** [comment]
@bd-dean thank you for the quick response.
