### ISSUE TITLE
Tabs on clearlinux.org

### ISSUE THREAD

**Issue by odwdinc** [clearlinux/clear-linux-documentation#1042]
When Clicking on the tabs under
https://clearlinux.org/developer

The page will open a new page.
This is in contrast to all other tabs on "About" and "Software"
While this my make seance for Developer->Documentation.
the is no need for Developer -> Community to launch a new window. 
going back to Developer -> Developer will not cause the new page.

Thoughts?

**Comment by mvincerx** [comment]
Thanks for testing this. I believe the [community.clearlinux.org](https://community.clearlinux.org/) , as in navigating from Developer->Community, may need a new URL because the Forum is managed by a third-party. I'll look into this. Let's discuss this in the Tues. morning meeting.

**Comment by intelkevinputnam** [comment]
@mvincerx This should be resolved. Please check. Links on the Forum and in the documentation already work as requested (no new tabs). Now the only odd link out is the link to Documentation from the Developer tabs, which still opens a new tab. Need to decide whether we would like this link to behave the same way.

**Comment by mvincerx** [comment]
Confirmed  that `Developer>Community` UI behavior works fine.  Nice work. Thanks!
I think you, @krisdale, and I should discuss UI behavior of Documentation tab. Keeping this open until we decide as a team.

**Comment by mvincerx** [comment]
Confirmed closed.
