### ISSUE TITLE
Correct the link in the Kata tutorial

### ISSUE THREAD

**Issue by mvincerx** [clearlinux/clear-linux-documentation#1044]
**Describe the error/improvement to an existing document or image**
Doc: https://docs.01.org/clearlinux/latest/tutorials/kata.html?highlight=kata

Refer to: https://community.clearlinux.org/t/broken-link-referencing-kata-tutorials/3454

**Comment by puneetse** [comment]
This was originally reported from: https://community.clearlinux.org/t/broken-link-referencing-kata-tutorials/3454/2

**Comment by intelkevinputnam** [comment]
Please note that the problem is not with the documentation page, but with the copy of the tutorial page that is here: https://community.clearlinux.org/t/run-docker-on-clear-linux-os/229

Which, not surprisingly, is out of date.

**Comment by mvincerx** [comment]
@pixelgeek Please advise !

**Comment by pixelgeek** [comment]
Tutorial post has been deprecated, and a link posted to https://docs.01.org/clearlinux/latest/tutorials/docker.html instead.
