### ISSUE TITLE
clrtrust documentation

### ISSUE THREAD

**Issue by puneetse** [clearlinux/clear-linux-documentation#1048]
**Do you think Clear Linux documentation needs a new document? Please describe.**

Please add a document about how to use clrtrust. 
There is documentation on the project's README. It would be nice to create man pages and have documentation on the website.
https://github.com/clearlinux/clrtrust/blob/master/README.md

**Should the new document be a guide, a reference, or a tutorial?**
Guide

**Additional context**
https://community.clearlinux.org/t/how-to-add-new-trusted-ca-certificate-to-clear-linux/3457

@bryteise FYI

**Comment by puneetse** [comment]
Manpage PR https://github.com/clearlinux/clrtrust/pull/21

**Comment by mvincerx** [comment]
Dependent on manpages.
