### ISSUE TITLE
Software packages bundles-about doesn't redirect to 01.org\~

### ISSUE THREAD

**Issue by aberusugi** [clearlinux/clear-linux-documentation#1049]
**Describe the error/improvement to an existing document or image**
When you attempt to use legacy links on clearlinux.org, there is no redirect currently to get you to the correct place in docs (which formerly was located on clearlinux.org, but is presently on 01.org). 

For instance, starting at the software bundles --> https://clearlinux.org/software/bundle/desktop

When you click "bundles in Clear Linux OS" which links here -> https://clearlinux.org/documentation/clear-linux/concepts/bundles-about

This results in a 404, when the proper link maybe is -> https://docs.01.org/clearlinux/latest/guides/clear/bundles.html - Or something like that.

There may be more links than this, I'm sure someone could scan for:

`https://clearlinux.org/documentation*`

Among all of the pages' links on clearlinux.org to evaluate the scope of the problem.

**Screenshots**
N/A

**Environment (please complete the following):**
Firefox Browser on Win10Pro Feature Update 1909

**Additional context**

**Comment by krisdale** [comment]
The correct redirect has been put in place.

**Comment by mvincerx** [comment]
Thank you, @krisdale!
