### ISSUE TITLE
Update to FAQ

### ISSUE THREAD

**Issue by pixelgeek** [clearlinux/clear-linux-documentation#1059]
Add the question: 

"What Distro is Clear Linux based on?"

Would be a good opportunity to dispel rumours and outline some of the underlying architecture.  
See also - https://community.clearlinux.org/t/clear-linux-closest-relative-distribution/3576/7

**Comment by puneetse** [comment]
It will also be a good opportunity to include these:
https://community.clearlinux.org/t/why-does-clearlinux-use-swupd-and-not-apt-deb-rpm/3284?u=puneetse

https://community.clearlinux.org/t/does-clear-linux-os-use-the-intel-compiler-icc-tl-nope/3301?u=puneetse

**Comment by mvincerx** [comment]
I fully support this addition. The first link, re swupd, verges on beautiful prose to my ears. What a lucid argument on the case for a different Linux arch. design.  Links from [our FAQ page](https://docs.01.org/clearlinux/latest/FAQ/index.html) to these posts are good for everyone.
