### ISSUE TITLE
Guide specifies insecure steps for converting/installing images

### ISSUE THREAD

**Issue by bwarden** [clearlinux/clear-linux-documentation#107]
https://github.com/clearlinux/clear-linux-documentation/blob/78571ea4dc1cbb774294c8663803a2604d4eb77d/source/clear-linux/get-started/virtual-machine-install/vmware-esxi-preconfigured-cl-image.rst#L83

Both of these steps are highly discouraged by VMware:
- SSH into the ESXi host as root
- running vmkfstools on the ESXi host

We should rework the guide to perform the conversion elsewhere (if it's still necessary), and remove this section completely.

**Comment by tpleavitt** [comment]
@bktan8 , have you had a chance to look into this?

**Comment by bktan8** [comment]
I have been looking into it, but no resolution yet.

**Comment by tpleavitt** [comment]
Documentation addresses this
