### ISSUE TITLE
Add manpage hyperlink where commands are used in all docs

### ISSUE THREAD

**Issue by mvincerx** [clearlinux/clear-linux-documentation#1073]
**Describe the error/improvement to an existing document or image**

Add a link in CL documentation to the current manpage in GitHub (where possible). 
- Validate commands to assure docs match current manpage; if errors or discrepancies, file issue associated GH repo
- Contact repo/tool maintainer if questions 

**Screenshots**
NA

**Additional context**

Example: Update swupd
CL Docs: https://docs.01.org/clearlinux/latest/guides/clear/swupd.html 
GitHub: https://github.com/clearlinux/swupd-client/blob/master/docs/swupd.1.rst

**Comment by mvincerx** [comment]
Closed per meeting 05-06-2020

**Comment by lebensterben** [comment]
>Closed per meeting 05-06-2020

@mvincerx 05-05-2020
