### ISSUE TITLE
Update mixer doc to add "bundle definition" and remove references to Docker.

### ISSUE THREAD

**Issue by bktan8** [clearlinux/clear-linux-documentation#1084]
* Under the "Bundles" section, add "Bundle definition" section to explain what can go into a bundle definition.

* Remove content related to Docker since mixer no longer uses container to make mix.  

* Use includes to link the new info from `swupd-3rd-party` to `mixer` doc. Give privilege to latest info in `swupd-3rd-party`

**Comment by mvincerx** [comment]
For 3rd bullet above, refer to: https://github.com/clearlinux/clear-linux-documentation/pull/1075#pullrequestreview-377135728

**Comment by bktan8** [comment]
@mvincerx - here's the writeup on bundle definition:

Bundle definition

What goes into a bundle is defined what is known as a “bundle definition” file.  The format
of a bundle definition file consists of a header section, which provides information about 
about the bundle and does not have direct effect on the bundle itself, followed by a list of packages and directives.  The directives are:

* :command:`include(<required-bundle-name>)` - Add <required-bundle-name> with this bundle
* :command:`also-add(<optional-bundle-name>)` - Add <optional-bundle-name> with this bundle unless the :command:`swupd bundle-add` option :command:`--skip-optional` is used.  
* :command:`content(</full/path/to/non-packaged/content)` -  Add the non-packaged content to the bundle.  This is useful for building `3rd-party bundles`_. 

Here is an example of an upstream bundle definition:

.. code-block:: console

# [TITLE]: cluster-tools
# [DESCRIPTION]: Utilities to manage computer clusters
# [STATUS]: Active
# [CAPABILITIES]: HPC
# [TAGS]: Tools and Utilities
# [MAINTAINER]: Juro Bystricky <juro.bystricky@intel.com>

# required bundles
include(curl)
include(libglib)
include(libX11client)

# optional bundles
also-add(openmpi)
also-add(modules)

# packages
munge
pmix
pdsh
slurm

.. _3rd-party bundles:
https://docs.01.org/clearlinux/latest/guides/clear/swupd-3rd-party.html
