### ISSUE TITLE
reference of  the file `/usr/share/defaults/httpd/httpd.conf`  in the stateless page is not present on a live CLR OS

### ISSUE THREAD

**Issue by lsandov1** [clearlinux/clear-linux-documentation#1089]
**Describe the error/improvement to an existing document or image**

In the stateless document, this line points to the following file `/usr/share/defaults/httpd/httpd.conf`

https://github.com/clearlinux/clear-linux-documentation/blob/master/source/guides/clear/stateless.rst#id28

but looking into this file on today's (`32660`) CLR OS, file does not exit. My recommendation is to pick another conf file as reference.

**Environment (please complete the following):**

```
# cat /usr/lib/os-release
NAME="Clear Linux OS"
VERSION=1
ID=clear-linux-os
ID_LIKE=clear-linux-os
VERSION_ID=32660
PRETTY_NAME="Clear Linux OS"
ANSI_COLOR="1;35"
HOME_URL="https://clearlinux.org"
SUPPORT_URL="https://clearlinux.org"
BUG_REPORT_URL="mailto:dev@lists.clearlinux.org"
PRIVACY_POLICY_URL="http://www.intel.com/privacy"
BUILD_ID=32660
```
**Additional context**

**Comment by mvincerx** [comment]
I'm reviewing this. Thanks.
