### ISSUE TITLE
 Add a docker pull command in dbrs guide.

### ISSUE THREAD

**Issue by mvincerx** [clearlinux/clear-linux-documentation#1099]
**Describe the error/improvement to an existing document or image**

 Add a docker pull command in relevant sections. 

https://docs.01.org/clearlinux/latest/guides/stacks/dbrs.html

@VictorRodriguez please advise on correct location to add these.

**Comment by mvincerx** [comment]
Hi @bd-dean. 
How are your [dog and cat getting along](https://www.youtube.com/watch?v=JmzuRXLzqKk)? 

@VictorRodriguez and I worked together on the DBRS blogpost from last week. He mentioned he wanted to add some `docker pull` commands here. Could you please work with him on this?

**Comment by VictorRodriguez** [comment]
Sure, sorry I was busy with other stuff

**Comment by mvincerx** [comment]
No worries. I'm just trying to help folks connect. We'll revisit this issue in our Docs meeting today, and report back.

**Comment by VictorRodriguez** [comment]
@mvincerx I can see now that the web page has the section Release with this line:

Refer to the `Database Reference Stack website`_ for information and download links for the different versions and offerings of the stack.

It linsk to the right place : https://clearlinux.org/stacks/database-reference

With the correct docker pull commands (thanks to you): 
      docker pull sysstacks/dbrs-memcached-clearlinux:latest    Copied
      docker pull sysstacks/dbrs-memcached-centos8:latest    

I think we can close this issue 

What do you think ?

**Comment by mvincerx** [comment]
Hey @VictorRodriguez.  Thanks for checking back. 

Mande? No tenemos que mantener la lucha!

j/k   Sure we can close this. Just wanted to make sure that you were satisfied with the doc. 📄
