### ISSUE TITLE
nvidia.rst: Disable `Wayland` for `gdm`

### ISSUE THREAD

**Issue by lebensterben** [clearlinux/clear-linux-documentation#1101]
According to this [report](https://github.com/clearlinux/distribution/issues/1780#issuecomment-591076452), installing NVIDIA proprietary driver may increase boot time on Optimus laptop, if `Wayland` is not disabled for `gdm`.

One one hand,
1) This problem greatly affect user experience. So it seems worth documenting this issue to me.
2) Currently `gdm` always uses `Xorg` so disabling `Wayland` is harmless.

But on the other hand, 
1) I don't think many users managed to install proprietary driver on Optimus laptops in the first place.
2) I'm not aware of this issue on non-Optimus devices. Should this be a bug then we should not document this but to report the bug to upstream.

**Comment by puneetse** [comment]
May be it's something to add to the Troubleshooting section as a tip/note.

**Comment by SPAstef** [comment]
I don't know how many users had the patience to investigate this, so that's probably why there are not reports about it, although the number of Optimus laptop, worldwide, should be quite considerable...

**Comment by mvincerx** [comment]
> May be it's something to add to the Troubleshooting section as a tip/note.
I like @puneetse 's idea of adding a line here:
https://docs.01.org/clearlinux/latest/tutorials/nvidia.html#troubleshooting
