### ISSUE TITLE
Update swupd command in fix broken install document

### ISSUE THREAD

**Issue by puneetse** [clearlinux/clear-linux-documentation#1106]
**Describe the error/improvement to an existing document or image**
The document to fix broken install (https://docs.01.org/clearlinux/latest/guides/maintenance/fix-broken-install.html) needs to have `--statedir=/mnt/var/lib/swupd` added to the `swupd repair` command.

**Additional context**
https://community.clearlinux.org/t/clearlinux-boot-logs-login-issue/4078/3?u=puneetse

**Comment by mvincerx** [comment]
Thanks for spotting this need for a fix.
