### ISSUE TITLE
https://clearlinux.org/documentation/clear-linux/get-started -> 404

### ISSUE THREAD

**Issue by taschenlampe** [clearlinux/clear-linux-documentation#1107]
![image](https://user-images.githubusercontent.com/10836480/78190583-93079f00-7474-11ea-8311-feb9ebeb9e15.png)

I was looking a little though the https://cdn.download.clearlinux.org/  page there is a page called https://cdn.download.clearlinux.org/README.html, it mentions a site called: https://clearlinux.org/documentation/clear-linux/get-started that cannot be found(404)

**Comment by mvincerx** [comment]
@mdpitterle, Do you have the means to contact our CDN provider? This is outside the scope of our docs.

**Comment by mdpitterle** [comment]
@taschenlampe @mvincerx - this has been corrected.

**Comment by mvincerx** [comment]
Fixed. Thanks for finding this error.

**Comment by mvincerx** [comment]
Consider contributing to our docs: https://docs.01.org/clearlinux/latest/collaboration/collaboration.html

**Comment by mvincerx** [comment]
@gtkramer rocks!

**Comment by mvincerx** [comment]
And so do you, @mdpitterle. 👍
