### ISSUE TITLE
nvidia.rst : Add description for multiple GPUs on Laptop

### ISSUE THREAD

**Issue by benschneider** [clearlinux/clear-linux-documentation#1118]
Problem: when following current guide on a Laptop with integrated GPU, the OS won't boot correctly any longer.

Solution: Disable integrated GPU when activating NVIDIA GPU.

**Comment by lebensterben** [comment]
> Getting NVIDIA Optimus* on Linux working well with both graphics devices adds an additional level of complexity with platform specific steps and may require additional software. Installation for systems with NVIDIA Optimus* with both graphics devices operating is not covered by the scope of this documentation. As a simple workaround, some systems can disable one of the graphics devices or NVIDIA Optimus* in the system firmware.

Do you have a laptop with NVIDIA Optimus?

https://github.com/clearlinux/clear-linux-documentation/blob/master/source/tutorials/nvidia.rst

**Comment by benschneider** [comment]
What I meant is to add a short description on how to disable the internal GPU in case this happens. 
As in: 
reboot, 
press alt+F2, 
login and add/modify modprobe? 
What would you suggest ?

BIOS/EFI usually does not let you disable a graphics card.

**Comment by lebensterben** [comment]
>What I meant is to add a short description on how to disable the internal GPU in case this happens.  ...

@benschneider Did you manage to disable your integrated GPU? If so, how?

**Comment by mvincerx** [comment]
> What I meant is to add a short description on how to disable the internal GPU in case this happens.
> As in:
> reboot,
> press alt+F2,
> login and add/modify modprobe?
> What would you suggest ?

@benschneider, Yes, we're interested in the steps it took to disable an internal GPU when activating NVIDIA, as @lebensterben states above.  Of course, once we understand what exactly you did and that it worked, we'll test it too.

**Comment by benschneider** [comment]
Not yet. Just formated it clean and reinstalled the system (basic LTS no added software). Is there an experimental script or guide I should try?

**Comment by mvincerx** [comment]
Clear Linux OS doesn't have an LTS.  Did you mean you used the LTS kernel? 
Maybe you meant that you followed one of these guides to install the OS? 

- https://docs.01.org/clearlinux/latest/get-started/bare-metal-install-server.html
- https://docs.01.org/clearlinux/latest/get-started/bare-metal-install-desktop.html

In case you haven't read this NVIDIA tutorial, I recommend it (I wondered if you already followed it): 
https://docs.01.org/clearlinux/latest/tutorials/nvidia.html

See [Known Issues](https://docs.01.org/clearlinux/latest/tutorials/nvidia.html#known-issues) for systems with multiple GPUs.

**Comment by benschneider** [comment]
> Clear Linux OS doesn't have an LTS. Did you mean you used the LTS kernel?
> Maybe you meant that you followed one of these guides to install the OS?
> 
>     * https://docs.01.org/clearlinux/latest/get-started/bare-metal-install-server.html
> 
>     * https://docs.01.org/clearlinux/latest/get-started/bare-metal-install-desktop.html
> 
> 
> In case you haven't read this NVIDIA tutorial, I recommend it (I wondered if you already followed it):
> https://docs.01.org/clearlinux/latest/tutorials/nvidia.html
> 
> See [Known Issues](https://docs.01.org/clearlinux/latest/tutorials/nvidia.html#known-issues) for systems with multiple GPUs.

The system I am using is (Lenovo Laptop Y720-KB -> NVIDIA Optimus).

For the installation I followed https://docs.01.org/clearlinux/latest/get-started/bare-metal-install-desktop.html
to install the OS. 
This works perfectly. 

On the initial run I did follow the instruction given here 
https://docs.01.org/clearlinux/latest/tutorials/nvidia.html#installation
Driver file used:
https://download.nvidia.com/XFree86/Linux-x86_64/440.82/NVIDIA-Linux-x86_64-440.82.run
However this was not an LTS Kernel and Clear-linux-native-5.6.3-936
Result was :  "Oh no! Something has gone wrong" Message.

Now I wiped it and reinstalled the OS with the LTS Kernel.

I noticed you also have a script in development located here: https://github.com/lebensterben/awesome-clear-linux/tree/master/NVIDIA-Driver
Should I try this one with the same driver?

**Comment by lebensterben** [comment]
>> Clear Linux OS doesn't have an LTS. Did you mean you used the LTS kernel? ...

@benschneider That script just does everything the tutorial mentioned. You have to find a way to disable you integrated GPU, otherwise it won't work.
There's only one person I know that get it disabled, in BIOS.

**Comment by benschneider** [comment]
I think I will do some more experimenting then.
Thanks for the quick response anyhow.

**Comment by mvincerx** [comment]
Thanks, @lebensterben, for pointing out the subtleties of this and for posting your scripts.
