### ISSUE TITLE
Tutorial: Create mirror of upstream repo

### ISSUE THREAD

**Issue by bktan8** [clearlinux/clear-linux-documentation#1133]
Document how to mirror the upstream repo and how to configure clients to point to it.

**Comment by mvincerx** [comment]
Please take a look at Clear Distro Factory doc.

**Comment by lebensterben** [comment]
I suggest linking this somewhere in Clear Linux's documentation site, and make it more visible.

By showing people how you maintain this distribution,
first it increases the transparency and mitigates some people's concerns,
and also gives 3rd-party repo maintainer a good example.
