### ISSUE TITLE
Update the WordPress tutorial

### ISSUE THREAD

**Issue by bktan8** [clearlinux/clear-linux-documentation#1138]
* Update the code-blocks that are "bash" to "none" for mariaDB CLIs.  

* Reference * 
https://docs.01.org/clearlinux/latest/tutorials/wordpress/web-server-install.html#web-server-install

**Comment by mvincerx** [comment]
Please preserve path for: https://docs.01.org/clearlinux/latest/tutorials/wordpress.html
And remove extra landing page. 
Thanks @intelkevinputnam
