### ISSUE TITLE
Broken link on downloads page

### ISSUE THREAD

**Issue by pixelgeek** [clearlinux/clear-linux-documentation#1139]
**Describe the error/improvement to an existing document or image**
https://clearlinux.org/downloads

Section for:
IoT Edge Single Node
Clear Linux Edge Stack - Single Node 

Documentation link points to 
https://clearlinux.org/documentation/clear-linux/tutorials/greengrass
which is 404.  

Should point to https://docs.01.org/clearlinux/latest/guides/stacks/greengrass.html 

...although we may want to not have this section on the download page at all, as this stack is not being actively maintained any may be subject to bit rot.

**Comment by mvincerx** [comment]
I coordinated the fix.  Apparently, I'll need to be granted permissions to officially make changes to Column 2 of the [Downloads page](https://clearlinux.org/downloads).  For now, broken link fixed.
