### ISSUE TITLE
Deprecate OpenVINO tutorial, OpenVINO no longer supported in CL 

### ISSUE THREAD

**Issue by mvincerx** [clearlinux/clear-linux-documentation#1166]
**Describe the error/improvement to an existing document or image**
https://docs.01.org/clearlinux/latest/tutorials/openvino.html

Validate tutorial works. Please test all commands . Pay extra attention to whether the model fails because of possible dependency issues.  
Refer to: https://community.clearlinux.org/t/openvino-tutorial-not-working/4457

**Additional context**
Refer to: https://community.clearlinux.org/t/openvino-tutorial-not-working/4457

**Comment by lebensterben** [comment]
I had tried to simply modify the version check but that won't work, because there seems to have some breaking changes in Python libraries.

**Comment by mvincerx** [comment]
Currently reviewing status of `computer-vision-basic`, the bundle under which OpenVINO was included.
