### ISSUE TITLE
Align bare-metal-install-* with clr-installer new feature, verify-iso-integrity

### ISSUE THREAD

**Issue by mvincerx** [clearlinux/clear-linux-documentation#1185]
**Describe the error/improvement to an existing document or image**

Add new section `Verify integrity of installer media` in: 
https://docs.01.org/clearlinux/latest/get-started/bare-metal-install-desktop.html
https://docs.01.org/clearlinux/latest/get-started/bare-metal-install-server.html

Align CL Docs with clr-installer with release of:
- PR: https://github.com/clearlinux/clr-installer/pull/737 
- Issue: https://github.com/clearlinux/clr-installer/issues/490

**Screenshots**
TBD: New screenshot forthcoming to replace Figure 1.

**Environment (please complete the following):**
 - Clear Linux OS version: 33210

**Additional context**

**Comment by karthikprabhuvinod** [comment]
@mvincerx : Thanks for making the changes. LGTM.
