### ISSUE TITLE
Remove  "Is ZFS Available?," FAQ , after ZFS tut is published

### ISSUE THREAD

**Issue by mvincerx** [clearlinux/clear-linux-documentation#1194]
**Describe the error/improvement to an existing document or image**

Post-publication of ZFS tutorial, remove section "Is ZFS Available?" from FAQ :
https://docs.01.org/clearlinux/latest/FAQ/index.html#is-zfs-available

**Screenshots**
NA

**Environment (please complete the following):**
NA
 - Third-party tool/software: [version]
 - Command [ [e.g. `sudo -i`]

**Additional context**

**Comment by puneetse** [comment]
Waiting for https://github.com/clearlinux/clear-linux-documentation/pull/1174 to merge
