### ISSUE TITLE
typo in performance guide (url specified)

### ISSUE THREAD

**Issue by krunch3r76** [clearlinux/clear-linux-documentation#1201]
Dear Clear Linux Project team, I constructively feel the documentation can be enhanced by addressing the following grammatical error:
[https://docs.01.org/clearlinux/latest/guides/clear/performance.html#aggressive-compiler-flags](url)
under subheading "mtune and march", 2nd paragraph:

Clear Linux OS defines **it’s** minimum hardware requirements to be second-generation Intel® microarchitecture code name Westmere (released in 2010) or later.

The boldfaced item is a contraction and does not express the possessive as expected. I recommend replacing with 'its'. Thank you for considering my recommendation.

**Comment by mvincerx** [comment]
Good observation. Thanks for the close reading. 
@krunch3r76,  we welcome community contributions.  So you can correct this error in a PR. Do you want to do so? 
Here's how: https://docs.01.org/clearlinux/latest/collaboration/collaboration.html#contribute-via-github

**Comment by krunch3r76** [comment]
@mvincerx i intend to correct the error in a PR now that you suggested it. thanks for the documentation link to help me see how i can!

**Comment by mvincerx** [comment]
Closed per #1204
