### ISSUE TITLE
typo in maintenance guide (url specified)

### ISSUE THREAD

**Issue by krunch3r76** [clearlinux/clear-linux-documentation#1202]
Dear ClearLinux team, I constructively feel the documentation can be enhanced by correcting the following typo:
https://docs.01.org/clearlinux/latest/guides/maintenance/configure-hugepages.html#configure-huge-pages
in Note frame, 3rd sentence
The madvise option means that hugepages are enabled for processes that **explicitely** call madvise.

This boldfaced item has been misspelled. Please consider replacing with 'explicitly'. Thank you for considering my recommendation.

**Comment by mvincerx** [comment]
@krunch3r76, thanks again for finding editorial errors.  Just as with #1201, do you want to correct this in a PR?
We welcome community contributions. To contribute, see: https://docs.01.org/clearlinux/latest/collaboration/collaboration.html#contribute-via-github

**Comment by krunch3r76** [comment]
PR #1203

**Comment by mvincerx** [comment]
Closed per #1203
