### ISSUE TITLE
links not working

### ISSUE THREAD

**Issue by mofm** [clearlinux/clear-linux-documentation#1210]
Documentation links are not working on the home page. Can you check please?

**Comment by lebensterben** [comment]
The section OP is referring to can be located by the following CSS selector:
`div.field:nth-child(5) > section:nth-child(1) > div:nth-child(1) > div:nth-child(1) > div`
or XPATH:
`/html/body/div[2]/div[3]/section/div/div/div[1]/div/div[5]/section/div[1]/div/div`

**Comment by mvincerx** [comment]
How about simply naming the title of the div/span/ul that doesn't work? 
I checked several, and I can't find one that it broken on the docs site: https://docs.01.org/clearlinux/latest/index.html

**Comment by lebensterben** [comment]
@mvincerx 
Well, it's actually not the documentation site `docs.01.org/clearlinux`
but the main site `clearlinux.org`

There's a section
```
Concepts

Learn in detail about the features that make Clear Linux OS different.

 

Guides

Step-by-step instructions on the different ways to use Clear Linux OS.

 

Tutorials

Thorough documentation on different use case scenarios of using Clear Linux OS.

 

References

Additional information on the Clear Linux OS project and features.
```
These links are broken.

**Comment by mvincerx** [comment]
Yeah, I just found it on the marketing site homepage: https://clearlinux.org/
 Thanks for your quick reply 
I fixed it so the links on the marketing site lead to the Clear Linux OS project documentation.
