### ISSUE TITLE
Steps missing for building dkms-zfs and zfsutils

### ISSUE THREAD

**Issue by ObscureScience** [clearlinux/clear-linux-documentation#1217]
The steps described in [source/tutorials/zfs.rst](https://github.com/clearlinux/clear-linux-documentation/blob/60d975b3fa54f0e9e8d5ce5ee6999f8dc5dad8af/source/tutorials/zfs.rst) were inadequate to build either the kernel modules or the userland tools. The necessery steps were quite straight-forward though.
A `./autogen.sh` before `sudo dkms build -m zfs -v $zfsver` did the trick.

I don't know if I'm missing something, but this sentence in step 4 makes no sense to me "In addition, this installs the zfs userspace tools too:" as I've never seen userland programs being built by dkms. This is remedied by the usual
```
./configure --prefix=/usr/local
make -j$(nproc)
sudo make install
```
...However this build the kernel modules again, which I can imagine steps on dkms' toes, and is probably not that great. But this works, including after reboot.

**Environment (please complete the following):**
 - Clear Linux OS version:

> NAME="Clear Linux OS"
> VERSION=1
> ID=clear-linux-os
> ID_LIKE=clear-linux-os
> VERSION_ID=34170
> PRETTY_NAME="Clear Linux OS"
> ANSI_COLOR="1;35"
> HOME_URL="https://clearlinux.org"
> SUPPORT_URL="https://clearlinux.org"
> BUG_REPORT_URL="mailto:dev@lists.clearlinux.org"
> PRIVACY_POLICY_URL="http://www.intel.com/privacy"
> BUILD_ID=34170

 
 - Third-party tool/software: zfs-2.0.1

**Comment by mvincerx** [comment]
https://github.com/clearlinux/clear-linux-documentation/blob/master/source/tutorials/zfs.rst recently updated.
