### ISSUE TITLE
404 file not found

### ISSUE THREAD

**Issue by pixelgeek** [clearlinux/clear-linux-documentation#1218]
The first link when searching for "Concepts" on clearlinux.org takes you to https://clearlinux.org/node/1704
Scrolling down and clicking on "See all the Concepts" link leads to a 404.  
Should probably redirect to clearlinux.org/about

**Comment by lebensterben** [comment]
similar to #1218 and #1210

**Comment by mvincerx** [comment]
We're aware of these and are working to resolve a backend server error. Thanks for your patience.

**Comment by arrow165317** [comment]
加油！

**Comment by mvincerx** [comment]
Fixed: https://clearlinux.org/developer

Concepts is replaced by the [About page on the Documentation website](https://docs.01.org/clearlinux/latest/about.html) 
This subsection in the marketing website refers to Documentation components, which give much more detail.
