### ISSUE TITLE
ERROR: Page not found

### ISSUE THREAD

**Issue by shaswata56** [clearlinux/clear-linux-documentation#1224]
There is a page not found error in the official [Clear Linux](https://clearlinux.org) website.

When following the link from [here](https://clearlinux.org/developer),
![Screenshot from 2021-05-04 23-18-55](https://user-images.githubusercontent.com/19504197/117044296-18244e00-ad30-11eb-9c73-d1c52570bd79.png)

The page redirects to [here](https://clearlinux.org/documentation/clear-linux/reference/how-to-clear-overview),
![Screenshot from 2021-05-04 23-20-55](https://user-images.githubusercontent.com/19504197/117044507-53bf1800-ad30-11eb-88cb-52b3b9903f3f.png)

**Comment by j1mc** [comment]
I could create a separate issue, but there are several broken links on the https://clearlinux.org/developer page.

**Comment by mvincerx** [comment]
Fixed: https://clearlinux.org/developer

**Comment by shaswata56** [comment]
thanks
