### ISSUE TITLE
wrong information

### ISSUE THREAD

**Issue by nobodyatandnothing** [clearlinux/clear-linux-documentation#1236]
https://docs.01.org/clearlinux/latest/guides/clear/telemetrics.html#id9
```
$ sudo swupd bundle-add telemetrics
$ sudo telemctl opt-in
sudo: telemctl: command not found
$ telemctl
telemctl: command not found
To install telemctl use: sudo swupd bundle-add devpkg-telemetrics-client

**Comment by phmccarty** [comment]
The `telemetrics-client` package was disabled from being included in the `telemetrics` bundle on Jan 4, which is why you're seeing this behavior.

https://github.com/clearlinux/clr-bundles/commit/f682a36cd1e40993077

**Comment by nobodyatandnothing** [comment]
Why?

**Comment by pixelgeek** [comment]
The telemetry server is currently offline and the client was removed to prevent error messages due to not being able to reach the server.
