### ISSUE TITLE
mailing list link on clearlinux.org is pointing to the staging site (403 error)

### ISSUE THREAD

**Issue by pixelgeek** [clearlinux/clear-linux-documentation#1243]
**Describe the error/improvement to an existing document or image**
[Provide a clear and concise description of the error or proposed improvement.
](https://stg.clearlinux.org/community/mailing-list: 403

should be:
https://clearlinux.org/community/mailing-list)
**Screenshots**
![image](https://user-images.githubusercontent.com/1402359/168873529-6f65c4fb-4ee9-445d-a54f-e8ec6c1fba6d.png)

**Environment (please complete the following):**
clearlinux.org)

**Additional context**

**Comment by mvincerx** [comment]
Fixed.
https://clearlinux.org/
