### ISSUE TITLE
Documentation Website Software Search not Returning Queries

### ISSUE THREAD

**Issue by cyberpika2** [clearlinux/clear-linux-documentation#1252]
https://clearlinux.org/software

Searching for any software or bundles functionality broken - does not return queries for software or bundles.
Example:
nginx - no results.

![image](https://user-images.githubusercontent.com/33668483/191508306-5f4423b0-57e6-46b9-858d-0f512a984480.png)

**Comment by pixelgeek** [comment]
Software search is now working.
