### ISSUE TITLE
Bundles list is very out of  date

### ISSUE THREAD

**Issue by matthewrsj** [clearlinux/clear-linux-documentation#126]
The available bundles file (https://github.com/clearlinux/clear-linux-documentation/blob/master/source/clear-linux/reference/bundles/bundles.html) is very out of date. Last updated October of 2017. We have added dozens of new bundles since then, including many pundles. Many of the includes have changed as well.

The effected external page is https://clearlinux.org/documentation/clear-linux/reference/bundles/available-bundles

It would probably not be difficult to write a script to generate this list instead of having to manually update it.

**Comment by matthewrsj** [comment]
> It would probably not be difficult to write a script to generate this list

Here's the script to get you includes per bundle:
```
for i in `sudo swupd bundle-list --all`; do echo $i && echo "===========" && unbundle $i <path/to/clr-bundles/repository/> --bundles && echo; done
```
Simple change to get you all packages in a bundle (including packages in the included bundles), just remove the --bundles flag:
```
for i in `sudo swupd bundle-list --all`; do echo $i && echo "===========" && unbundle $i ~/clearlinux/projects/clr-bundles && echo; done
```

**Comment by mltullis** [comment]
We have an old script we've used to generate an HTML table with all the latest bundle info. We're dusting that off and are looking at CI for ongoing use to keep this up to date. I'll have more info in a day or two.

**Comment by matthewrsj** [comment]
If your script was last used in October it wasn't taking pundles into consideration. Keep in mind that we now publish pundles via the clr-bundles/packages file as well. These are exposed as regular bundles to the user so should be reported in this page.

**Comment by mltullis** [comment]
Adding @mvincerx into this discussion.

**Comment by mvincerx** [comment]
I've got a new branch started with all updated bundles. Just learning how to include pundles.  I'm communicating with @matthewrsj

**Comment by mvincerx** [comment]
https://github.com/clearlinux/clear-linux-documentation/pull/127

**Comment by mltullis** [comment]
https://github.com/clearlinux/clear-linux-documentation/pull/127 is merged and goes live this afternoon. Part of this was a manual update. We'll continue to work on the automation.

**Comment by mvincerx** [comment]
@mltullis, @matthewrsj  advised me on a new way to bring in the "latest" bundles using the for loop he gives above. (I just have to re-install CL on my NUC to do so, and rebuild the HTML table manually again.) 
For this, I'll open a new PR since this one is merged.  Phase 2: Let's discuss the automation more next week.

**Comment by mvincerx** [comment]
@matthewrsj, if you have time this weekend, can you please advise?  See also my email. 

From where (in directory/ forked repo) do you run this command?: 
` for i in `sudo swupd bundle-list --all`; do echo $i && echo "===========" && unbundle $i <path/to/clr-bundles/repository/> --bundles && echo; done`

` for i in `sudo swupd bundle-list --all`; do echo $i && echo "===========" && unbundle $i <path/to/clr-bundles/repository/> --bundles && echo; done`

**Comment by matthewrsj** [comment]
> From where (in directory/ forked repo) do you run this command?

Doesn't matter, as long as you replace everything inside the `<...>` with the path to cloned `clr-bundles` repository. Let me give you a few more instructions.

Let's just do this in your home directory.
```bash
sudo swupd bundle-add os-clr-on-clr     # this gets you the unbundle tool
cd ~
git clone https://github.com/clearlinux/clr-bundles.git
for i in `sudo swupd bundle-list --all`; do echo $i && echo "===========" && \
        unbundle $i ~/clr-bundles --bundles && echo; done 1> bundles
```
Those commands above will throw the complete list of all Clear Linux bundles and their included bundles into the `bundles` file. You can view/edit this file by running
```
vi ~/bundles
```
Each section will look like this:
```
R-basic
===========
R-basic
libX11client
os-core
```
The first line is the title of the bundle, followed by a separator, followed by the recursively included bundles. Keep in mind this list will include the bundle itself (in this case `R-basic`) and the implicitly-included `os-core` bundle. You probably want to filter those out.

Let me know if you have any more questions.

**Comment by matthewrsj** [comment]
btw, you can just copy that command block and paste it into your terminal with no modification needed.

**Comment by mvincerx** [comment]
Thanks, Matthew. Silly me. I overlooked the embedded file path in the previous script. Too many PRs to complete by COB Friday. :)

**Comment by tpleavitt** [comment]
This issue has been resolved and there is an associate jira to track enhancements to this.
