### ISSUE TITLE
Broken Links on Clear Linux OS and Containers page

### ISSUE THREAD

**Issue by cpburnz** [clearlinux/clear-linux-documentation#1262]
**Describe the error/improvement to an existing document or image**

There a multiple broken links that 404 on [Clear Linux OS and Containers](https://clearlinux.org/downloads/containers).

Broken links:

- [bundles software](https://docs.01.org/clearlinux/latest/guides/clear/bundles.html) redirects to https://clearlinux.github.io/clear-linux-documentation/latest/guides/clear/bundles.html which is a 404.
- [our security page](https://docs.01.org/clearlinux/latest/guides/clear/security.html) redirects to https://clearlinux.github.io/clear-linux-documentation/latest/guides/clear/security.html which is a 404.
- [documentation about container images](https://docs.01.org/clearlinux/latest/get-started/containers/container-images.html) redirects to https://clearlinux.github.io/clear-linux-documentation/latest/get-started/containers/container-images.html which is a 404.
- [adding the containers-basic](https://docs.01.org/clearlinux/latest/tutorials/docker.html) redirects to https://clearlinux.github.io/clear-linux-documentation/latest/tutorials/docker.html which is a 404.
- [documentation about Docker on Clear Linux OS](https://docs.01.org/clearlinux/latest/tutorials/docker.html) redirects to https://clearlinux.github.io/clear-linux-documentation/latest/tutorials/docker.html which is a 404.
- [documentation about Kata on Clear Linux OS](https://docs.01.org/clearlinux/latest/tutorials/kata.html) redirects to https://clearlinux.github.io/clear-linux-documentation/latest/tutorials/kata.html which is a 404.
- [Kubernetes on Clear Linux OS](https://docs.01.org/clearlinux/latest/tutorials/kubernetes.html) redirects to https://clearlinux.github.io/clear-linux-documentation/latest/tutorials/kubernetes.html which is a 404.

**Comment by pixelgeek** [comment]
Thanks - we have multiple issues with the transition of our back end hosting for the documentation and the webpages.  I'll make sure to check these links as things settle out.

**Comment by hajes** [comment]
same here.

**Comment by SmokeyCosmy** [comment]
> Thanks - we have multiple issues with the transition of our back end hosting for the documentation and the webpages. I'll make sure to check these links as things settle out.

No idea what was checked since then but this issue isn't yet fixed.

**Comment by pixelgeek** [comment]
Closing this issue as obsolete.  The webpage https://clearlinux.org/downloads/containers is no longer linked from the Clear Linux website home page.
