### ISSUE TITLE
Broken documentation on the website

### ISSUE THREAD

**Issue by romanrm** [clearlinux/clear-linux-documentation#1268]
https://www.clearlinux.org/about.html has a link to https://www.clearlinux.org/documentation.html on the mid-right of the page.
At that destination, none of the links work and CSS is broken. All links lead to reload of the website main page.

**Comment by cloudymax** [comment]
seconded, all urls on https://www.clearlinux.org/ are broken and redirect back to https://www.clearlinux.org/. Its impossible to find how to use your project in this state

**Comment by djklimes** [comment]
Hum, the download, trademark, cookie and other links look fine but going through all the links I do see that autoproxy and telemetry links on the about page don't seem to resolve (but don't point back to about).  The css looks fine from internal and external.  What browser are you using?

**Comment by pixelgeek** [comment]
@djklimes Maybe they're referring to the broken css on the 'view all' of 'latest news'?

**Comment by romanrm** [comment]
On the https://www.clearlinux.org/documentation.html page, the error in my browser console is:

`The stylesheet https://www.clearlinux.org/ was not loaded because its MIME type, “text/html”, is not “text/css”.`

Looking into the source, the very first CSS link, does this:

```
$ curl -I https://clearlinux.org/clear-linux-documentation/_static/css/theme.css
HTTP/1.1 301 Moved Permanently
content-length: 0
location: https://www.clearlinux.org
x-haproxy-hostname: prd1haproxy04
```

**Comment by pixelgeek** [comment]
Hi @romanrm - you shouldn't have a link to "documentation.html" on the about page anymore - the documentation moved to "clear-linux-documentation/index.html"
https://github.com/clearlinux/clearlinux.github.io/commit/472380661e99ab7e47c0a01db1368c105665e08a

**Comment by romanrm** [comment]
Indeed, I see that the link on the about page has been corrected, thanks.
