### ISSUE TITLE
bootable-usb-linux guide should list only live and installer images

### ISSUE THREAD

**Issue by mrkz** [clearlinux/clear-linux-documentation#144]
Currently, only 2 images are build to be used in a USB stick:
 * `clear-<VERSION>-installer.img`
 * `clear-<VERSION>-live.img`

However, the [Create a bootable USB drive on Linux](https://clearlinux.org/documentation/clear-linux/get-started/bootable-usb/bootable-usb-linux) guide is a bit confusing about which images can be used on a USB stick by mentioning all Clear Linux* images available.

The proper guide should point out to create either an installer usb stick or a live usb stick using the `clear-<VERSION>-installer.img` or the `clear-<VERSION>-live.img` respectively, avoiding user to get confused with all image options Clear Linux* offers.

**Comment by tpleavitt** [comment]
@mrkz , this change will be merged to the website today.  Please review pull request https://github.com/clearlinux/clear-linux-documentation/pull/145 for the changes.  If this meets the requirement, feel free to close this issue once published.

**Comment by tpleavitt** [comment]
The documentation changes have been updated on the website
