### ISSUE TITLE
"not a sentence error" in swupd-about.rst

### ISSUE THREAD

**Issue by matthewrsj** [clearlinux/clear-linux-documentation#162]
The :ref: at https://github.com/clearlinux/clear-linux-documentation/blame/master/source/clear-linux/concepts/swupd-about.rst#L126 causes the following sentence in the rendered web page:
```
Therefore, we provide a Use mixer tool.
```

https://clearlinux.org/documentation/clear-linux/concepts/swupd-about

**Comment by mvincerx** [comment]
PR 187 closes Issue 162
https://github.com/clearlinux/clear-linux-documentation/pull/187
