### ISSUE TITLE
Consolidate documentation for image integrity and signature validation

### ISSUE THREAD

**Issue by phmccarty** [clearlinux/clear-linux-documentation#163]
(Original report at https://github.com/clearlinux/distribution/issues/85)

Two pages already exist to document the related topics of verifying image checksum signatures and image integrity:
- [How to verify Clear Linux image integrity.](https://clearlinux.org/documentation/clear-linux/get-started/bare-metal-install#verify-the-integrity-of-the-clear-linux-image)
- [How to validate the signature of a Clear Linux image checksum file.](https://clearlinux.org/documentation/clear-linux/guides/maintenance/validate-signatures#image-content-validation) This section also covers image integrity verification, but a little differently.

It would be helpful for this documentation to be consolidated such that the steps are described in the same way.

**Comment by intelkevinputnam** [comment]
Hi @phmccarty 

It looks like the version in the bare metal install is missing the verification of the certificate. Would you recommend simply including the section from the guide section in the bare metal? I've verified that the bare metal install works as advertised, but I haven't walked through the maintenance guide version.

**Comment by phmccarty** [comment]
@intelkevinputnam Sure, I am okay with including the guide doc section on the bare metal page. The primary ask is to have the same information available (or linked to) on both pages, for consistency.

**Comment by intelkevinputnam** [comment]
Added the following line and link to [Download, verify, and uncompress a Clear Linux image on Linux](https://clearlinux.org/documentation/clear-linux/guides/maintenance/download-verify-uncompress-linux), which is the source for the section in bare metal install: "For a more in-depth discussion of image verification including checking the certificate see [Image content validation](https://clearlinux.org/documentation/clear-linux/guides/maintenance/validate-signatures#image-content-validation)."

**Comment by pohly** [comment]
Also note that there are technical issues with the openssl command (https://github.com/clearlinux/distribution/issues/85#issuecomment-395354903) and the current SHA512SUM file no longer works with the `sha512sum -c` command (https://github.com/clearlinux/distribution/issues/85#issuecomment-400601494).

The former might be worth mentioning in the documentation if it can't be fixed. The later probably should be fixed in the SHA512SUM files.
