### ISSUE TITLE
write clear linux web server tutorial

### ISSUE THREAD

**Issue by mvincerx** [clearlinux/clear-linux-documentation#166]
@mvincerx. Create a new tutorial on" creating a Clear Linux web based server" to support autospec and mixer guides. Current tutorial here does not support aforementioned guides: 
https://clearlinux.org/documentation/clear-linux/tutorials/web-server-install#web-server-install

**Comment by tpleavitt** [comment]
This will be a good counterpoint using nginx instead of apache
