### ISSUE TITLE
Add instructions for root encrypted installation

### ISSUE THREAD

**Issue by mrkz** [clearlinux/clear-linux-documentation#180]
starting from installer version 22600, Clear Linux* now supports full disk encryption, but current documentation does not provide details about this new use case.

Plase add this new install case into the proper documentation page for installing clearlinux.

I'm adding the screenshots of the install for using disk encryption.

![keyboard_selection](https://user-images.githubusercontent.com/978752/42045719-dcfa4c6a-7ac1-11e8-949a-40c8a313f46d.png)

![network_requirements](https://user-images.githubusercontent.com/978752/42045724-e157181a-7ac1-11e8-90d9-da7f2ab35b65.png)

![installer_action](https://user-images.githubusercontent.com/978752/42045733-e526c9d6-7ac1-11e8-8a2e-c257cc28d3f4.png)

![telemetry_opt-in](https://user-images.githubusercontent.com/978752/42045738-e7ba6bbc-7ac1-11e8-9758-d98650fb9b10.png)

![select_install_type](https://user-images.githubusercontent.com/978752/42045741-ea76f726-7ac1-11e8-8258-c6856ca93398.png)

![select_partitioning_method](https://user-images.githubusercontent.com/978752/42045745-ed71e3aa-7ac1-11e8-8316-3d1e485e5175.png)

![select_drive_to_partition](https://user-images.githubusercontent.com/978752/42045747-efd3d0f4-7ac1-11e8-98a6-81dbca6a2fa7.png)

![cgdisk_partition_summary](https://user-images.githubusercontent.com/978752/42045753-f3296c1e-7ac1-11e8-8d00-e059348935b5.png)

**Please notice the following screen lists the new feature as a check-box to encrypt the root partition**

![set_mount_points](https://user-images.githubusercontent.com/978752/42045760-f7f50a0a-7ac1-11e8-9484-efcb92be78c6.png)

![set_root_encryption_passphrase](https://user-images.githubusercontent.com/978752/42045770-fbb5f276-7ac1-11e8-9e41-2c0b564334a9.png)

![kernel_boot_cmdline](https://user-images.githubusercontent.com/978752/42045779-ffd552a2-7ac1-11e8-9d66-0a318806a548.png)

![set_hostname](https://user-images.githubusercontent.com/978752/42045785-033f8516-7ac2-11e8-95a9-4e22c2f8e25e.png)

![user_configuration](https://user-images.githubusercontent.com/978752/42045795-0a0e6588-7ac2-11e8-92b3-1b5867c9597c.png)

![select_bundles_to_install](https://user-images.githubusercontent.com/978752/42045798-0d7881f4-7ac2-11e8-93a5-21db6b652b45.png)

![select_network_configuration](https://user-images.githubusercontent.com/978752/42045852-3313f52e-7ac2-11e8-8491-55c56a21303b.png)

![start_installation_confirmation](https://user-images.githubusercontent.com/978752/42045863-362885b8-7ac2-11e8-9a4e-3cb593e7cdbd.png)

**Comment by tpleavitt** [comment]
@mvincerx , can you please look into adding this content

**Comment by mvincerx** [comment]
Closed per https://github.com/clearlinux/clear-linux-documentation/pull/267
