### ISSUE TITLE
VirtualBox step missing in docs?

### ISSUE THREAD

**Issue by undeadindustries** [clearlinux/clear-linux-documentation#210]
When trying to run install-vbox-lga, it asks for gcc, perl and linux headers.

The Dev bundle solves gcc and perl.

But I can't sort out how to install the linux headers. I've downloaded the source for the LTS release of the kernel. I've installed the linux bundles.

I'm totally stumped. Any help would be appreciated.

Thanks!

**Comment by mvincerx** [comment]
@puneetse.  Would you have time to review this?

**Comment by mvincerx** [comment]
@undeadindustries. Thanks for raising this concern. Both a colleague and I are looking into this. We'll report back during the week of 13 Aug.

**Comment by puneetse** [comment]
@undeadindustries while we are reconciling the documentation, please try the latest Clear Linux version if you haven't already.

The kernel and script have been updated by @bwarden to resolve some issues that were being seen .

**Comment by tpleavitt** [comment]
Issue resolved with PR217
