### ISSUE TITLE
Problems installing the default DE following instructions on the website

### ISSUE THREAD

**Issue by Alec423** [clearlinux/clear-linux-documentation#237]
I tried installing clearlinux on a compatible laptop (or so did the compatibility tester .sh file say) and on VMware Player 14. In both cases I followed the guides on the [clearlinux](https://clearlinux.org) website, first the [installation one](https://clearlinux.org/documentation/clear-linux/get-started/bare-metal-install) and second the '[Create and enable a new user space](https://clearlinux.org/documentation/clear-linux/guides/maintenance/enable-user-space
)' one. In both cases I arrived at the point where I would need to submit `systemctl start gdm` and, after putting my account's password and authorizing the thing, literally nothing would happen. Same thing trying with xinit or startx.

**Comment by puneetse** [comment]
@Alec423 are you still experiencing this issue?

If so, I'd suggest opening an issue under https://github.com/clearlinux/distribution/issues to troubleshoot in detail. Please include the version of ClearLinux and Xorg logs if possible. 

Also, feel free to join the #clearlinux IRC channel on freenode when someone may be able to jump in and help faster.

**Comment by Alec423** [comment]
@puneetse Yes, I'm still experiencing the issue, I have opened [this](https://github.com/clearlinux/distribution/issues/210) new issue on the section you suggested

**Comment by puneetse** [comment]
@Alec423 Thanks. It looks like there has been some correlation with other GitHub issues already. I'm going to close this issue out since it doesn't appear to be related to documentation (yet) but rather may be an actual distribution bug.
