### ISSUE TITLE
Document custom kernel modifications

### ISSUE THREAD

**Issue by tpleavitt** [clearlinux/clear-linux-documentation#249]
From distribution created by [shrmrf](https://github.com/shrmrf) : clearlinux/distribution#215  

**Is your feature request related to a problem? Please describe.**
Documentation which describes (tutorial style perhaps) modification of the Linux kernel, adding and signing kernel modules is missing.

**Describe the solution you'd like**
- Tutorial on how with best-practices for Linux Kernel modification
- Kernel module signing documentation etc.
- Compiling a kernel module to run against Clear Linux

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Comment by shrmrf** [comment]
@tpleavitt cool, thanks!!

**Comment by mrkz** [comment]
@tpleavitt @miguelinux would be worth to add to this documentation also how to add custom cmdline kernel parameters.

**Comment by miguelinux** [comment]
We use those targets ;-)

`menuconfig`, `oldconfig` , `olddefconfig`

**Comment by tpleavitt** [comment]
I asked one of our engineers about this and he replied as follows:

Our kernel packages include a configuration file that is fed into the build (https://github.com/clearlinux-pkgs/linux/blob/master/config) and when the kernel is installed in the system, the config is also stored in /usr/lib/kernel. If you're building the kernel yourself, you can certainly use `menuconfig` to modify the config file.

As part of the build, we run `make olddefconfig` to ensure that the ingested config is complete and correct. The copy that is stored in the package repo, which is input to this step, is typically generated through an automated process that similarly ends with `olddefconfig`, but this file is also subject to manual verification before we commit it.

**Comment by shrmrf** [comment]
Thanks @tpleavitt + @miguelinux  can you elaborate a bit more? 

Maybe in tutorial style format? Where do we start (which repo?) and how can we use `make menuconfig` with it.. etc. etc.??

**Comment by tpleavitt** [comment]
We added this document a few weeks ago and will continue to review other documentation that can be added to the website specific to kernel modifications.
[Add kernel modules](https://clearlinux.org/documentation/clear-linux/guides/maintenance/kernel-modules)

**Comment by mvincerx** [comment]
@tpleavitt. Checking in.  Do you want to leave this issue open, or did we satisfy requirements?

**Comment by tpleavitt** [comment]
@shrmrf , can you take a look at [PR#383](https://github.com/clearlinux/clear-linux-documentation/pull/383) mentioned above to see if this satisfies your request?

**Comment by shrmrf** [comment]
@tpleavitt yeah! I think this is what I was looking for all along... 

Haven't tried the steps but the doc looks very good already
