### ISSUE TITLE
Edits needed for the "Create a Clear Linux* based web server" tutorial

### ISSUE THREAD

**Issue by krisdale** [clearlinux/clear-linux-documentation#256]
Reorg of the WordPress tutorial (PR #247 ) prompted a request for edits to the first part of the tutorial from @odwdinc. 

Edits to the content of the tutorial will be done as a separate PR. 

Requested changes: 

**1. Current content:** 
    Open a text editor and perform the following:
    Copy the content listed below into the new file /etc/httpd/conf.d/httpd.conf. 
    **Question:** 
    How do you open the text editor? as this is a procted file and you will need root the dir dus not excit 
    so you need to creat the dir befor you can add the file.
    **Suggestion/comment:**

    sudo mkdir -p /etc/httpd/conf.d
    sudo nano /etc/httpd/conf.d/httpd.conf

**2. Current content:**
    To ensure a successful setup, edit the new index.html file. Change the original text from
    “This web server is operational from host.”
    to
    “This web server is operational from its new location.”
    **Suggestion/comment:**
    would be good to have the command agen to reinforce the need for sudo.
    the dafualt text is worng as the it is "It works!"

    sudo nano ./index.html 

**3. Current content:**
    Create a file named phpinfo.php in the /var/www/html/ directory using a text editor.
    Add the following line to the file:

    <?PHP phpinfo() ?>
 **Suggestion/comment:**
    As this dir is oned by root you will need to creat and edit the file with sudo.

    sudo nano /var/www/html/phpinfo.php 

**4. Current content:** 
    To check the status of MariaDB, enter the following command:
    sudo systemctl status mariadb
    **Suggestion/comment:**
    no shown way to exit this status.
    you will need to press 'ctrl+c' or 'q' to exit

**5. Current content:**
    To add a basic layer of security, enter the following command:

    mysql_secure_installation
    
**Suggestion/comment:**
    fresh install is not have blank password, cant get passt

**Comment by tpleavitt** [comment]
Documentation on the website has been updated and poublished
