### ISSUE TITLE
Kubernetes Tutorial Part II

### ISSUE THREAD

**Issue by mvincerx** [clearlinux/clear-linux-documentation#272]
**Do you think Clear Linux documentation needs a new document? Please describe.**

For someone who’s new to K8S, should there be a Kubernetes Tutorial Part II? Should we show how to?: 
-	Add an  overlay network
-	Join two nodes
-	Deploy a containerized application

Refer to discussion btw: @bktan8 , @joselamego , and @mvincerx.

**Should the new document be a guide, a reference, or a tutorial?**
Recommend a type of document, based on the structure here: 

Tutorial 

**Describe or provide examples of similar documents, if possible, from other web sites**
See current k8s tutorial: https://clearlinux.org/documentation/clear-linux/tutorials/kubernetes

https://github.com/clearlinux/clear-linux-documentation/pull/255

**Comment by tpleavitt** [comment]
Modify part 1 to include this content instead of creating a new document.

**Comment by pdxjohnny** [comment]
Part one was never modified to include this. Also, upon finishing the master installation and running `kubeadm join` on a node https://clearlinux.org/documentation/clear-linux/tutorials/kubernetes#use-your-cluster my nodes never changes from the NotReady status (`kubectl --kubeconfig /etc/kubernetes/kubelet.conf get nodes`) Also, I found nodes need to have the `containers-basic` bundle installed.

Are there plans to update the original documentation? I'm assuming someone is running nodes as well as their master, how was that done? I feel as though I'm missing something.
