### ISSUE TITLE
Getting Startwd Guide has non-working example

### ISSUE THREAD

**Issue by uudruid74** [clearlinux/clear-linux-documentation#284]
URL https://clearlinux.org/documentation/clear-linux/get-started/bare-metal-install#bare-metal-install

Curl example gives a 404...

    curl -O https://download.clearlinux.org/image/clear-$(curl https://download.clearlinux.org/latest)-installer.img.xz

**Comment by tpleavitt** [comment]
Looking at latest it shows 25920 but the installer image only shows as 25800 in the image directory.  They are out of sync.  I'll report this to our build team.

**Comment by tpleavitt** [comment]
The downloads site is now back in sync

**Comment by tpleavitt** [comment]
This pointed out an issue with how releases are tagged in the download directory with regards to which latest image is available depending on the type of release.  There is a file in the image directory named latest-images which lists the image files that are currently in the image directory.  The documentation will need to be updated to correctly parse this file to get the true latest image depending on the type.  The correct way to automate this is to use the following command:

curl -O https://download.clearlinux.org/image/$(curl https://download/clearlinux.org/image/latest-images | grep "installer")

**Comment by tpleavitt** [comment]
All documentation using this method has been updated to correct method.  See pull requests 285-289
