### ISSUE TITLE
Incorrect bundle name on latest OpenVINO/Greengrass document

### ISSUE THREAD

**Issue by poussa** [clearlinux/clear-linux-documentation#302]
**Describe the error/improvement to an existing document or image**

The new document https://clearlinux.org/documentation/clear-linux/tutorials/greengrass has an error in adding the bundles:

`swupd bundle-add os-clr-on-clear desktop-autostart computer-vision-basic`

Should be

`swupd bundle-add os-clr-on-clr desktop-autostart computer-vision-basic`

**Comment by iphutch** [comment]
Thank you for the fix, @bd-dean
