### ISSUE TITLE
Add Alternative to Multiboot to Chain Grub

### ISSUE THREAD

**Issue by mmccool** [clearlinux/clear-linux-documentation#314]
**Describe the error/improvement to an existing document or image**
The current multiboot install instructions suggest disabling grub and modifying the menus in clr-boot-manager to boot other distributions using grub like Ubuntu.  However it's simpler to simply add a single menu item to let the clr-boot-manager to invoke grub if selected.   This also lets the target OS update its kernels, options etc. without having to change the configuration files for clr-boot-manager.   It also makes the configuration files for clr-boot-manager simpler since you don't have to copy over all the options, etc.   This does not even significantly slow down autonomous boot if you give both of them short timeouts (I use 5s for both).

For example, in my system, where I dual-boot an ubuntu installation in this way, I added only the following in `/boot/loader/entries/ubuntu.conf`:

    title Ubuntu
    efi /EFI/ubuntu/grubx64.efi

And now I never have to touch this again.

**Screenshots**
If applicable, add screenshots to help explain the error or unexpected behavior.

**Environment (please complete the following):**
NAME="Clear Linux OS"
VERSION_ID=26170

**Additional context**
There is a related issue with swupd that clears the timeout on the boot manager when you do an update.   There is an easy fix but I thought I would mention it here since it will affect people who are doing multiboot so maybe the workaround should also be documented in the same place:
https://github.com/clearlinux/swupd-client/issues/683

**Comment by linjiach** [comment]
Thanks for the suggestion! It's indeed much simpler. We will update tutorial.

**Comment by mvincerx** [comment]
Closed per GH-820
