### ISSUE TITLE
kubernetes: docker part needs a revisit

### ISSUE THREAD

**Issue by mythi** [clearlinux/clear-linux-documentation#327]
**Describe the error/improvement to an existing document or image**
cloud-native-basic bundle does not install docker (through dependencies) anymore so extra steps is needed in the doc to have docker (containers-basic) installed.

**Environment (please complete the following):**
 - Clear Linux OS version: [VERSION_ID=26410]

**Comment by tpleavitt** [comment]
@mvincerx , can this issue be closed?

**Comment by mvincerx** [comment]
@tpleavitt . I'm waiting for the answer to that question from @mythi . :)

**Comment by mythi** [comment]
@mvincerx @tpleavitt OK to close!
