### ISSUE TITLE
Recommend different OVMF.fd sources for different host OSes

### ISSUE THREAD

**Issue by gtkramer** [clearlinux/clear-linux-documentation#333]
**Describe the error/improvement to an existing document or image**
https://clearlinux.org/documentation/clear-linux/get-started/virtual-machine-install/kvm

For the above document, the preferred approach for a Clear Linux host to use OVMF.fd is to copy it from /usr/share/qemu/OVMF.fd to the working directory.  For non-Clear Linux hosts, the preferred approach is to download it from https://cdn.download.clearlinux.org/image/OVMF.fd.

**Screenshots**
N/A

**Environment (please complete the following):**
 - Clear Linux OS version: Any version
 - Third-party tool/software: N/A
 - Command: N/A

**Additional context**
This should be done to help address the version fragmentation we're experiencing with this file, as mentioned in [a distribution issue](https://github.com/clearlinux/distribution/issues/113).

**Comment by mvincerx** [comment]
Closed per GH-385.
