### ISSUE TITLE
Add link to increase disk size in the Next Steps section of Getting Started/Install VM

### ISSUE THREAD

**Issue by tpleavitt** [clearlinux/clear-linux-documentation#360]
Add link to increase the disk size in the Next Steps section of Getting Started/Install Clear Linux OS in a virtual machine.  The link is: https://clearlinux.org/documentation/clear-linux/guides/maintenance/increase-virtual-disk-size

**Comment by mvincerx** [comment]
@MCamp859 will work on this. 
@MCamp859 in your PR, please add a separate line that states: "Closes #360".
Doing so will automatically close this issue as soon as your PR is merged.

**Comment by mvincerx** [comment]
Closed per https://github.com/clearlinux/clear-linux-documentation/pull/361
