### ISSUE TITLE
Missing step in DLRS tutorial 

### ISSUE THREAD

**Issue by bd-dean** [clearlinux/clear-linux-documentation#364]
If you strictly follow the instructions in the DLRS tutorial, the steps to clone and then run the TF benchmarks will fail.  Need to add a first step to run the docker image: 

docker run --name <image name>  --rm -i -t <clearlinux/stacks-dlrs-TYPE> bash

[https://clearlinux.org/documentation/clear-linux/tutorials/dlrs](DLRS tutorial)

**Comment by mvincerx** [comment]
Closed per GH-365. 
https://github.com/clearlinux/clear-linux-documentation/pull/365
