### ISSUE TITLE
Need to add DKMS instructions

### ISSUE THREAD

**Issue by bwarden** [clearlinux/clear-linux-documentation#369]
**Describe the error/improvement to an existing document or image**
We have introduced DKMS support for out-of-tree kernel module building. We should add instructions for installing the bundle, using the dkms tool to build and install out-of-tree modules, and how to update them. We should also mention that installing the bundle disables module signature verification, show the message it adds to the MOTD, and explain how to disable that feature, if necessary.

**Additional context**
Probably should add content [here](https://github.com/clearlinux/clear-linux-documentation/blob/a4bd78a0ede04f009e9f9dd54c2c98b14428da2c/source/clear-linux/guides/maintenance/kernel-modules.rst#build-and-load-an-out-of-tree-module).

[Basics on using DKMS](https://wiki.archlinux.org/index.php/Dynamic_Kernel_Module_Support)

User will need to bundle-add `kernel-native-dkms`, which:
* provides the `dkms` tool
* provides (via include) the very large `linux-dev` bundle, which includes the files necessary to build out-of-tree modules against the native kernel.
* adds an update trigger `/usr/lib/systemd/system/dkms-new-kernel.service` to automatically run dkms to rebuild modules after a kernel upgrade
* adds (via `/usr/share/kernel/cmdline.d/clr-ignore-mod-sig.conf`) a kernel command-line argument, `module.sig_unenforce`, that disables kernel module signature verification, allowing out-of-tree modules to be loaded.
  * This has security implications
  * This can be disabled via `/etc/kernel/cmdline-removal.d/*.conf` (see `clr-boot-manager` manpage), but will result in _not_ being able to load dkms-built modules.

After installing the bundle for the first time, the user will have to run `sudo clr-boot-manager update` manually to apply the kernel command line change. This is called from swupd when a new kernel is installed, but not merely by installing this bundle.

**Comment by bwarden** [comment]
It might also be good to write a tutorial showing how to install the NVIDIA drivers, for example.

**Comment by tpleavitt** [comment]
@bwarden I was just thinking that when you first posted this.  Could you write the step by step commands and I can then take that and make a tutorial out of it.

**Comment by bwarden** [comment]
I _could_, but the installer detects whether you have supported hardware (I don't), so the resulting sequence is a bit different. I can give you that sequence anyway, at least as a head start.

**Comment by tpleavitt** [comment]
That would be great.  I'll talk to you on Monday.  Is the dev-utils bundle all I would need to be able to run make for this or are there other bundles needed to be able to compile the new kernel?  I want to be able to all the requirements documented in the tutorial to run this from start to finish.

**Comment by bwarden** [comment]
Ah, good point, we probably also need c-basic. Maybe I should include that in the bundle.

**Comment by bwarden** [comment]
Sample process:

1. Select and download the appropriate Linux 64-bit driver package from the NVIDIA site
1. Agree to the terms and download the driver package, noting the location where it was saved
1. Open a shell in the directory where the package was saved
1. Run the installer package (sudo sh ./NVIDIA-Linux-x86_64-XXX.XX.run)
   1. When prompted, register the driver with DKMS
   1. Continue with the installer until it uses DKMS to install the kernel module

**Comment by bwarden** [comment]
Ideally we'd get the installer to register/build the kernel modules, but not dump its libraries or other binaries into /usr. I'm playing around with installer options, and theoretically this should work, but it's not obeying all the options:
`sudo ./nvidia-installer --no-nvidia-modprobe --no-distro-scripts --no-opengl-files --no-libglx-indirect --no-install-libglvnd --dkms -s`

**Comment by mvincerx** [comment]
Hi there. This sounds like it would make an interesting addition to our existing guide here: 
https://clearlinux.org/documentation/clear-linux/guides/maintenance/kernel-modules

@puneetse Given that you worked on the above `kernel-modules` doc, would you be willing/able to take on Brett's request to create a guide and install `kernel-native-dkms` and add the  `nvidia` drivers?

**Comment by bwarden** [comment]
Yes, that's where it should go. Also, this command line for the installer looks better:
`sudo ./nvidia-installer --no-nvidia-modprobe --no-distro-scripts --no-opengl-files --no-libglx-indirect --no-install-libglvnd --no-install-compat32-libs --dkms --ui=none`
...although it still prompts whether to register with DKMS (which the arg `--dkms` is supposed to force)

**Comment by mvincerx** [comment]
Hi @tpleavitt, @puneetse. Can you please give me a status update? I just need to know if someone's working on it. Thanks.

**Comment by tpleavitt** [comment]
@mvincerx Let me take a swing at it now that the meetup is over.  I'll get with @bwarden next week and start on it.
