### ISSUE TITLE
Install Clear Linux* OS on bare metal missing last install step

### ISSUE THREAD

**Issue by krisdale** [clearlinux/clear-linux-documentation#387]
In the "Finish installation" section, the last step to set up root account is missing. 

Need to add this step back in (instructions and screenshot is available in git history https://github.com/clearlinux/clear-linux-documentation/tree/c21f3b93013cc72ea550db5ec41c8268a0cfd66d , from Nov 2018)

**Comment by mvincerx** [comment]
Great. I'll take this. I'll integrate a recommendation to create an Admin User and flesh our detail at the end.

**Comment by tpleavitt** [comment]
This was in the original bare metal installer and was pulled out and moved to https://clearlinux.org/documentation/clear-linux/guides/maintenance/enable-user-space

**Comment by mvincerx** [comment]
@krisdale and I discussed options for a revision. In short, I'll add a couple recommendations, such as installing `desktop-autostart`, just like we did in the EAP. Give me some time to propose some changes. I'll probably touch `enable-user-space` too.

**Comment by tpleavitt** [comment]
Sounds good.  The enable-user-space was created before the desktop-autostart bundle ever existed so a rewrite of that would be worth doing

**Comment by mvincerx** [comment]
Yep. I had this on a separate TODO list; but thanks to you all, it's now consolidated.

**Comment by mvincerx** [comment]
Closed per release of GH-393.
