### ISSUE TITLE
Kubernetes Setup Tutorial: don't try to start kubelet before kubeadm

### ISSUE THREAD

**Issue by pdxjohnny** [clearlinux/clear-linux-documentation#388]
test: don't try to start kubelet before kubeadm

Starting kubelet before kubeadm isn't necessary and while it worked in
the past, it no longer does with Clear Linux 26630 / Kubernetes 1.12
(/var/lib/kubelet/config.yaml not found,
clearlinux/distribution#310).

Reference: https://github.com/intel/oim/commit/b625d0a57c68a042c250d7723b443ddfbba94d06

**Comment by mvincerx** [comment]
@ mythi, I believe we address this in GH-376, in the note after "Update the control plane."  Can you please verify that this addresses @pdxjohnny 's concern?

**Comment by mythi** [comment]
@mvincerx this refers to https://clearlinux.org/documentation/clear-linux/tutorials/kubernetes#configure-and-run-kubernetes

The ask is to remove
```sudo systemctl restart kubelet``` in step 2.

That ask makes sense

**Comment by mvincerx** [comment]
Edit applied in GH-393. PR pending approval from @mythi.

**Comment by mvincerx** [comment]
Confirmed that this step was removed in GH-393. Closed.
