### ISSUE TITLE
Odd arguments about package management with other distros

### ISSUE THREAD

**Issue by eero-t** [clearlinux/clear-linux-documentation#399]
Following document: https://clearlinux.org/documentation/clear-linux/concepts/swupd-about

Has odd arguments about  package management "issues" with other distributions (i.e. what advantages swupd / bundles would have compared to them):

* "This can be done effectively, but given the nearly endless combinations of packages and versions of packages a server may have, it quickly becomes non-trivial to define what “version” the system is and what software it is running without explicitly going through each system and inspecting every package."

* "This matters on a daily basis to system administrators, who need to determine which of their systems do not have the latest security fixes, or which combinations of software have been tested."

For example, on Debian / Ubuntu:

* Checking whether available security updates have been installed, can be seen with "apt update" command (which is shorter command than "swupd check-update")

* If maintainer just wants everything to have the latest security updates, s/he just enables automatic security updates

* If s/he wants more control, machines s/he maintains get packages from a mirror / proxy in her/his control (which is updated from upstream only after testing, or where packages are "hand-picked")

So basically the "advantages" boil into swupd providing a single number for identifying the distribution package content.  However, that's not really useful as it doesn't tell anything.

As far as I can see, there's no way in ClearLinux to find out relevant things corresponding to its distro version:
* Does it have version of Y (or newer) of package B, which got the feature my app would need?
* Does it include version X of package A with a known security vulnerability?
* Does it have patch applied that fixes the issue?

E.g. in Debian/Ubuntu:
* "dpkg -s <package>" shows the package upstream version
* "apt source <package>" fetches package sources for more in-depth examination
* there's also a www-site where one can check which package versions are in which distro versions, their changelogs, included files, applied changes and a list of package specific bugs:
 ** https://packages.ubuntu.com/
 ** https://packages.debian.org/

**Comment by puneetse** [comment]
@eero-t thank you for the feedback! As you highlighted, the goal of the document is to explain why Clear Linux packages and updates software the way it does and point out the benefits. The goal and language isn't meant to accuse that everyone would have experienced these pain points on other distros. 

I think the order in which the information in the "Versioning" section is presented can be revised to make sure the focus is on Clear and mention some missing benefits, like package dependency resolution. Of course it's important that we remain humble and not overestimate, so I appreciate you bringing this up and if you have any specific changes you think should be made in the document please let us know! 

With the later points around package versioning and patches, it would be a better discussion if you can raise the issues here: https://github.com/clearlinux/distribution/issues.

**Comment by mvincerx** [comment]
Hi @eero-t. Thanks for your feedback on [swupd-about](https://clearlinux.org/documentation/clear-linux/concepts/swupd-about).  We're planning to revise some descriptions of the Clear Linux* OS features related to `swupd`, thanks in part to your feedback. 

Some questions you ask in the penultimate bullet list are already under consideration.  Please be patient. 

Swupd, and `swupd update` specifically, offers users several benefits. One benefit of this is that a single number in a Clear Linux OS release confirms that all package dependencies are resolved at build time. This saves developers the work of resolving conflicts by themselves. 

At the bottom of [Downloads](https://clearlinux.org/downloads)  is a link to Clear Linux OS releases:
https://cdn.download.clearlinux.org/releases/. Feel free to explore.  

If, for example, you wanted to see versions of packages for the most current release. You may go here: https://cdn.download.clearlinux.org/releases/current/clear/source/. Then download and view the `packages-sources` file. 

HTH

**Comment by eero-t** [comment]
> At the bottom of Downloads is a link to Clear Linux OS releases: https://cdn.download.clearlinux.org/releases/.

Ok, great, while this info isn't on the ClearLinux installation itself, it's at least now easily accessible.  And to see what patches/changes have been applied, I can download and extract the source packages.

(I was surprised to see that you're still building Mesa with autotools when Debian/Ubuntu have switched their builds to faster meson/ninja already 3 months ago.)

> One benefit of this is that a single number in a Clear Linux OS release confirms that all package dependencies are resolved at build time. This saves developers the work of resolving conflicts by themselves.

The cases where people need to do manual "package dependency resolving"  are after they install packages from somewhere else than their distro's own repositories.  If one wants to install packages from elsewhere to ClearLinux, *they need to be building ClearLinux themselves*.  Yes, you don't then have dependency problems in your target device, but you need to do large amount of additional work before hand.  To me that's a difference, rather than an advantage (avoid problem by hand-cuffing the user).

Or did I misunderstand the problem being solved?

**Comment by phmccarty** [comment]
> (I was surprised to see that you're still building Mesa with autotools when Debian/Ubuntu have switched their builds to faster meson/ninja already 3 months ago.)

Clear Linux uses autospec to build mesa, and autospec must select autotools as the build pattern instead of meson. Selecting a build system when multiple options are available is autospec's choice, unless a build pattern is forced via the `build_pattern` config file. As far as I recall, autospec didn't give preference to meson over autotools.

**Comment by mvincerx** [comment]
> The cases where people need to do manual "package dependency resolving" are after they install packages from somewhere else than their distro's own repositories. If one wants to install packages from elsewhere to ClearLinux, _they need to be building ClearLinux themselves_. Yes, you don't then have dependency problems in your target device, but you need to do large amount of additional work before hand. To me that's a difference, rather than an advantage (avoid problem by hand-cuffing the user).
> 
> Or did I misunderstand the problem being solved?
In fact, much of our documentation is geared toward Linux developers 
> who do build a Clear Linux image themselves for a variety of use 
> cases. Developer Workstation shows a brief overview of some of user 
> roles, and bundles relative to role, which may be of help to you.
> Using mixer, developers can build a custom OS  for a specific use case 
> and act as their own OSV, if they choose. We feel the flexibility 
> mixer offers, along with our autospec tool used to generate your own 
> RPMs, provides a lot of freedom. Yet, as with most things, “with 
> freedom comes great responsibility.”

In fact, much of our documentation is geared toward Linux developers who do build a Clear Linux image themselves for a variety of use cases. [Developer Workstation](https://clearlinux.org/documentation/clear-linux/guides/maintenance/developer-workstation) shows a brief overview of some of user roles, and bundles relative to role, which may be of help to you. Using [mixer](https://clearlinux.org/features/mixer-tool), developers can build a custom OS  for a specific use case and act as their own OSV, if they choose. We feel the flexibility mixer offers, along with our [autospec ](https://clearlinux.org/documentation/clear-linux/concepts/autospec-about) tool used to generate your own RPMs, provides a lot of freedom. Yet, as with most things, “with freedom comes great responsibility.”  We're constantly seeking to make it easier to the customize a Clear Linux OS implementation.

**Comment by eero-t** [comment]
> As far as I recall, autospec didn't give preference to meson over autotools.

Ok, if a tool does that decision instead of maintainer, then it makes sense to be conservative.

FYI: Git versions of few projects (Weston, Mesa...) require now an extra option if one wants to continue building them with Autotools, and will soon remove Autotools support completely.

**Comment by eero-t** [comment]
Checked the document changes.

Main error there is currently this:
"On a package-based OS, system administrators update each individual package or piece of software."

If it would instead say "... can update each individual...", it would match reality.

(Individual package update is done automatically by the package management SW for the administrator.  System administrators do "apt update && apt upgrade" to get upgrades, they don't upgrade things package-by-package unless they really want to.)

I assume that "extremely efficient" comment(s) apply to a future version of swupd which isn't anymore significantly slower than the packaging tools in other distros?   Document says swupd to be better in downloading the updated content, but the 60MB download (of metadata), which it seems to (almost)  always do before it starts doing the actual update, makes it slower than the other distros.
