### ISSUE TITLE
Package Bundle description missing

### ISSUE THREAD

**Issue by pixelgeek** [clearlinux/clear-linux-documentation#404]
https://clearlinux.org/documentation/clear-linux/reference/bundles is missing the description for dosfstools, even though there is a corresponding entry in https://github.com/clearlinux/clr-bundles/blob/master/packages (possibly because of a parenthesis that needs to be escaped?)

**Comment by mvincerx** [comment]
This is just a matter of running `bundle_lister.py`. I will split this into two tasks. 
- Submit update to current bundles and packages (to reflect latest data)
- Apply script revisions per #378
