### ISSUE TITLE
Sockets

### ISSUE THREAD

**Issue by victorstewart** [clearlinux/clear-linux-documentation#414]
Hi, just wondering how sockets work...

When I push say a 10MB packet over a socket… does the process...

A) push the entire packet of data into the operating system, and then move onto other tasks?

or B) feed the 10MB incrementally to the operating system, as requested?

I'm trying to reason about the order in which operations will occur on contentious sockets all managed by the same process.

**Comment by puneetse** [comment]
@bryteise @iphutch can you please move this into the main distribution issues (https://github.com/clearlinux/distribution) ?

**Comment by victorstewart** [comment]
yes will do! wasn't sure where to ask.
