### ISSUE TITLE
Clearlinux.org/stacks has duplicate picture

### ISSUE THREAD

**Issue by DnPlas** [clearlinux/clear-linux-documentation#442]
The stacks [main page](https://clearlinux.org/stacks) has a duplicate picture. We should replace the duplicate with the 'multi-node' image.

**Comment by bd-dean** [comment]
@DnPlas the second image is for PyTorch single node, while the first is TensorFlow.  We can replace the PyTorch with a MultiNode image if that's the right thing, can you confirm? 

Thanks!

**Comment by mvincerx** [comment]
@DnPlas. @bd-dean and I just talked, and she mentioned she'll add a note for clarity here. I always appreciate your contributions to the clear linux docs.  I just want to clarify: Going forward, please only file issues here that fall under this directory: https://clearlinux.org/documentation/clear-linux
Thanks

**Comment by DnPlas** [comment]
@bd-dean @mvincerx  agree, I'll close this issue.
