### ISSUE TITLE
Clearlinux.org/Wrong word "sytem" in clearlinux.org/documentation

### ISSUE THREAD

**Issue by coneypo** [clearlinux/clear-linux-documentation#448]
**Description**
It might be "system" rather than "sytem" in following link:
https://clearlinux.org/documentation/clear-linux/guides/maintenance/swupd-guide#example-3-verify-and-correct-sytem-file-mismatch

**Screenshots**
![image](https://user-images.githubusercontent.com/7233586/55717307-9b78f580-5a2b-11e9-9569-0864a6bc9edb.png)

**Environment**
 - Clear Linux OS version: clearlinux.org
 - Third-party tool/software: None
 - Command: None

**Additional context**
I found this error when I was visition clearlinux.org, and should i create issue for it in this repo?

Signed-off-by: Zhengtian Xie zhengtian.xie@intel.com

**Comment by mvincerx** [comment]
@coneypo Thanks for catching that typo!  Opened PR to correct it asap. See above. Please feel free to contribute to our docs.
