### ISSUE TITLE
Wireless connectivity

### ISSUE THREAD

**Issue by puneetse** [clearlinux/clear-linux-documentation#449]
It would be nice to have a document on the Clear Linux website that shows how to connect to a wireless AP as a client, using wpa_supplicant for example. 

It could highlight and document the current state of network managers in CL and how they may change when using WiFi. (e.g. systemd-networkd vs. NetworkManager)

**Should the new document be a guide, a reference, or a tutorial?**
Guide. 

**Describe or provide examples of similar documents, if possible, from other web sites**
https://wiki.archlinux.org/index.php/WPA_supplicant#Advanced_usage
https://shapeshed.com/linux-wifi/

**Additional context**
Both commandline and GUI examples would be useful.

**Comment by mvincerx** [comment]
@intelkevinputnam Will you please work with @puneetse on this? This is a lower priority, about P3/P4.

**Comment by intelkevinputnam** [comment]
Addressed by PR #882

**Comment by mvincerx** [comment]
@intelkevinputnam will work with @puneetse.
