### ISSUE TITLE
Kata containers setup guide has extra unnecessary steps

### ISSUE THREAD

**Issue by eadamsintel** [clearlinux/clear-linux-documentation#453]
https://clearlinux.org/documentation/clear-linux/tutorials/kata

Sometime in 2018 Clear Linux was updated so that the /etc/systemd/system/docker.service.d/50-runtime.conf is automatically created when you "sudo systemctl start docker" for the first time and that automatically creates the default runtime for Kata.  This information is still useful to have in the tutorial as a reference but it is automatically done and might be confusing.

**Environment (please complete the following):**
 - Clear Linux OS version: 28300 but also many older and newer versions

**Comment by mvincerx** [comment]
@eadamsintel. I'll take care of this.
