### ISSUE TITLE
Wrong shell command in YubiKey U2F support tutorial

### ISSUE THREAD

**Issue by lebensterben** [clearlinux/clear-linux-documentation#458]
**Error**

The 4th bullet point in section `Enable Linux udev rules for YubiKey` has a shell command, such as
```bash
sudo udevadm control --reload-rules && udevadm trigger
```
This won't work as the second statement `udevadm trigger` also needs root privilege. The correct one shall be
```bash
sudo udevadm control --reload-rules && sudo udevadm trigger
```

**Comment by mvincerx** [comment]
@lebensterben. Thank you for the feedback. I appreciate you carefully reviewing our documentation.

@puneetse or @odwdinc. Will you please review this? You both worked on the original document.

**Comment by puneetse** [comment]
Thanks for checking @lebensterben . I thought in my testing it worked without sudo but it makes sense that it would be required.

**Comment by mvincerx** [comment]
I'll take care of this.
