### ISSUE TITLE
Document installing VMware Workstation Pro on CL

### ISSUE THREAD

**Issue by puneetse** [clearlinux/clear-linux-documentation#462]
As suggested in https://github.com/clearlinux/distribution/issues/625, it would be nice for Clear Linux documentation to have a guide on installing VMware Workstation Pro on top of Clear Linux OS (making CL the host OS). 

VMware Workstation Pro is the commercial/paid version of the free VMware Player. 

**Should the new document be a guide, a reference, or a tutorial?**
Getting Started Guide

**Describe or provide examples of similar documents, if possible, from other web sites**
https://wiki.archlinux.org/index.php/VMware

**Additional context**

- Steps to reproduce and issues have been documented in https://github.com/clearlinux/distribution/issues/625.

- This has been made possible recently due to the work done around enabling custom kernel modules. 

- The LTS kernel should be the default recommendation for most likely comparability (similar to the VirtualBox documentation).

**Comment by mvincerx** [comment]
@krisdale Please take this one.

**Comment by krisdale** [comment]
@puneetse - would you please confirm that this is the same version/source you were able to successfully install in #625? https://my.vmware.com/web/vmware/details?downloadGroup=WKST-1504-LX&productId=799&rPId=31699

**Comment by puneetse** [comment]
@krisdale confirmed. The file name should be `VMware-Workstation-Full-15.0.4-12990004.x86_64.bundle`.

**Comment by krisdale** [comment]
@puneetse and I will work together to determine if this is best as a blog post or tutorial showing how to troubleshoot this sort of non-bundle installation that requires manual help.

**Comment by FabioMen10** [comment]
> @puneetse and I will work together to determine if this is best as a blog post or tutorial showing how to troubleshoot this sort of non-bundle installation that requires manual help.

I'm counting on it!

**Comment by mvincerx** [comment]
@krisdale will work with @puneetse .

**Comment by krisdale** [comment]
PR in progress.
