### ISSUE TITLE
Tutorial for Installing CUDA needed

### ISSUE THREAD

**Issue by lebensterben** [clearlinux/clear-linux-documentation#464]
A tutorial on how to install CUDA on Clear Linux is much needed.

The CUDA toolkit could accelerate certain machine learning routines greatly. Specifically, it could greatly improve the performance of TensorFlow-GPU.

Currently, the stable release of TensorFlow requires CUDA 10.0.There is a tutorial on [installation of NVIDIA proprietary driver](https://clearlinux.org/documentation/clear-linux/tutorials/nvidia). With several extra steps, one could successfully install CUDA 10.0.

Specifically, one needs to enable the `nvidia-modprobe` during installation, or otherwise CUDA would never run correctly. The following command works for me, and please verify it.

`sudo ./nvidia-installer --no-distro-scripts --no-opengl-files --no-libglx-indirect --no-install-libglvnd --no-install-compat32-libs --dkms --ui=none`

The real problem comes with the fact that, CUDA 10.0 doesn't work with GCC version > 7, while Clear Linux ships with GCC 8. A manual installation of GCC 7, along with GCC 8, is possible but it would rather be great if there's an official tutorial on it.

**Comment by mvincerx** [comment]
Hey @puneetse, Do you have the bandwidth for this?

**Comment by puneetse** [comment]
Now that GCC7 has been packaged in CL as part of the `c-extras-gcc7` this is possible.

**Comment by lebensterben** [comment]
> Now that GCC7 has been packaged in CL as part of the `c-extras-gcc7` this is possible.

I will write one when I got time.

**Comment by rana** [comment]
Any documentation on a successful cuda install and cudnn install would be appreciated.
I'm trying to work though it by combing a couple links. I know I'll work through it, but its slower without the guide. Thank you.

https://clearlinux.org/documentation/clear-linux/tutorials/nvidia#uninstalling-the-nvidia-drivers
https://www.reddit.com/r/ClearLinux/comments/b1gbbz/nvidiacuda_in_clear_linux_success_howto/

**Comment by lebensterben** [comment]
@rana 
1. First you need to install NVIDIA proprietary drivers and you can follow the Clear Linux tutorial. But you have to remove `--no-nvidia-modprobe` when you invoke the installation script. Alternatively, I've written some bash scripts to automate this, which is available [here](https://github.com/lebensterben/clear-linux/tree/TidyShell/NVIDIA-Driver)
2. If your kernel version is >5.0 and you want to have CUDA 10.0, then you need to install `c-extras-gcc7` bundle.
There is a compatibility matrix in CUDA's official documentation where you can see more information.
But note that Tensorflow only works with CUDA 10.0, at least as far as I know.
3. Then you need to install CUDA 10.0, its patch, and other utilities like `cuDNN` and `tensorRT`.
The latter two are easy to install. And as for CUDA 10.0, you shall download one `*.run` file, and on the download page you may freely choose any distribution as long as the architecture is matches yours.
Then `cd` into the directory where the `*.run` file is located in and execute `./<the name>.run --help` and you will see an option that allows you to only extract without installation.
If I recall correctly, you will get several directories with NVIDIA driver (which is outdated and we don't need it), CUDA toolkit itself, and an IDE. Go to the directory with CUDA toolkit and find the executable, execute `./<the name> --help`. Configure it as you like and you shall not have much trouble installing CUDA as long as you specified the path to `gcc7`.

I'm occupied by other stuff so I haven't got time to write the tutorial. But if you have any question you can post it here.

**Comment by rana** [comment]
Thank you for making the time to post such clear and detailed instructions.

**Comment by puneetse** [comment]
@lebensterben FYI I started writing up the documentation for this. I'll add you for optional review when the PR is ready.

**Comment by rana** [comment]
FYI, some hurdles which may or may not be relevant.

I had a Clear Linux installation fail after `swupd update` with Nvidia drivers and cuda installed. Not clear why. Had native kernel and `gcc` file linked to gcc-8. Not sure if native kernel update did not like nvidia kernel module or that recompile kernel with gcc-8 was the cause? Or something else? Have not seen clear instructions on how to install `kernel-lts` or if it is required for nvidia driver/cuda.

Second time around I have `native kernel` and left gcc file linked to gcc 9.1, and gcc-8 file linked to `cuda-gcc`. That seems to have worked for now. I am somewhat apprehensive to update the system and have the installation fail a second time. 

Here is the script I'm currently using. Looking forward to a recommended approach. 

Thank you

```sh
#!/bin/bash
# cuda_10.1.168_418.67_linux.run
NAME=cuda
PREFIX="--- $NAME:"
VER_KIT=10.1.168
VER_DRV=418.67
SRC_FLE=${NAME}_${VER_KIT}_${VER_DRV}_linux.run
OPT_DIR=/opt/$NAME
EXTRACT_DIR=/home/rana/Downloads/$NAME

echo "$PREFIX start"
echo "VER_KIT: $VER_KIT"
echo "VER_DRV: $VER_DRV"
echo "SRC_FLE: $SRC_FLE"
echo "OPT_DIR: $OPT_DIR"

echo "$PREFIX loading prerequisites"
sudo swupd bundle-add c-extras-gcc8

echo "$PREFIX extracting"
if [ -d "$EXTRACT_DIR" ]; then
    sudo rm -rf "$EXTRACT_DIR"
fi
if [ -d "$OPT_DIR" ]; then
    sudo rm -rf "$OPT_DIR"
fi
sudo mkdir "$EXTRACT_DIR"
sudo sh ./"$SRC_FLE" --extract="$EXTRACT_DIR" --override
sudo cp -r "$EXTRACT_DIR"/cuda-toolkit "$OPT_DIR"
# sudo rm -rf "$EXTRACT_DIR"
sudo ls "$OPT_DIR"

echo "$PREFIX environment variables"
ENV_DIR=/etc/profile.d
ENV_FLE=$ENV_DIR/$NAME.sh
EXPORT1="export PATH=\$PATH:$OPT_DIR/bin"
EXPORT2="export CUDA_PATH=$OPT_DIR"
EXPORT3="export LD_LIBRARY_PATH=\$LD_LIBRARY_PATH:$OPT_DIR/lib64"
if [ ! -d "$ENV_DIR" ]; then
    sudo mkdir "$ENV_DIR"
fi
sudo touch $ENV_FLE
if ! grep -q "$EXPORT1" $ENV_FLE ; then 
	echo "$PREFIX: writing: $ENV_FLE"
	sudo echo $EXPORT1 | sudo tee --append $ENV_FLE
    sudo echo $EXPORT2 | sudo tee --append $ENV_FLE
    sudo echo $EXPORT3 | sudo tee --append $ENV_FLE
fi

# # for knet cuda compile  https://denizyuret.github.io/Knet.jl/latest/install/#Installation-1
# cuda-gcc used by CUDAapi.jl
echo "$PREFIX compiler alias"
sudo ln -s /usr/bin/gcc-8 /usr/bin/cuda-gcc
cuda-gcc --version


echo "$PREFIX done"
```

**Comment by lebensterben** [comment]
> @lebensterben FYI I started writing up the documentation for this. I'll add you for optional review when the PR is ready.

@puneetse thx

**Comment by lebensterben** [comment]
> Thank you for making the time to post such clear and detailed instructions.
> 
> FYI, `c-extras-gcc8` can compile [CUDA 10.1](https://docs.nvidia.com/cuda/cuda-installation-guide-linux/index.html).

`CUDA 10.1` works with `gcc8` but `tensorflow` doesn't support `CUDA 10.1`. 

BTW, you can compile `CUDA 10.1` or `CUDA 10.0` even with `gcc9` but anything needs `CUDA` won't run.

**Comment by pldelisle** [comment]
Hi,

I have a problem with installing CUDA on a freshly installed Clear Linux.

The NVIDIA Driver is correctly installed and working. 

When I follow the [Tutorial](https://docs.01.org/clearlinux/latest/tutorials/nvidia-cuda.html#debugging), installation fails with `Installation failed. See log at /var/log/cuda-installer.log for details.`

Here is the log file.

[cuda-installer.log](https://github.com/clearlinux/clear-linux-documentation/files/3501653/cuda-installer.log)

Folders are empty after that. 

Any idea to solve my problem ? 

Thanks a lot.

**Comment by lebensterben** [comment]
>Hi, ...

@pldelisle when you install the driver, do you disabled modprobe?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by mns6070** [comment]
I am having the same issue as @pldelisle.  Cuda-installer.log is attached.
[cuda-installer.log](https://github.com/clearlinux/clear-linux-documentation/files/3753757/cuda-installer.log)

**Comment by lebensterben** [comment]
> I am having the same issue as @pldelisle. Cuda-installer.log is attached.
> [cuda-installer.log](https://github.com/clearlinux/clear-linux-documentation/files/3753757/cuda-installer.log)

Specifically, errors starts at line 19430, where it reports failures when installing CUDA samples.

I enabled `modprobe` when installing NVIDIA driver, and it seems to me that without it I cannot compile any CUDA samples.

Would you try reinstalling the driver without disabling `modprobe`?

**Comment by mns6070** [comment]
I tried installing the driver with and without the modprobe flag and it did not make a difference.

**Comment by lebensterben** [comment]
> I tried installing the driver with and without the modprobe flag and it did not make a difference.

If you don't need to develop CUDA programs, that is just use CUDA as a library, then you can disable the building of examples.

**Comment by mns6070** [comment]
Building without the samples flag worked.
