### ISSUE TITLE
Hard to find older download versions of Clear Linux, confusing when you do

### ISSUE THREAD

**Issue by dbkinder** [clearlinux/clear-linux-documentation#465]
**Describe the error/improvement to an existing document or image**
The Clear Linux download page seems to only provide downloads for the latest version.  (A project I'm working on depends on a particular version of Clear Linux.)  It's **very easy** to miss (as I did) that, way down at the bottom of the page there's a tiny mention of "Previous releases are available"
![image](https://user-images.githubusercontent.com/11063618/56699930-7384c580-66ac-11e9-9bea-e2605ce398de.png)

Compare this, for example with Ubuntu Desktop download site where you find not only the latest release (19.04) but also the last LTS release (18.04.02) and clear mention of "past releases" and a link to them:
![image](https://user-images.githubusercontent.com/11063618/56700035-fc036600-66ac-11e9-8bbc-5a739b78bf4f.png)

Also, when looking at older releases of Ubuntu you're shown a page that's approachable and readable, while for Clear Linux, previous releases are an unapproachable and confusing (oddly sorted) list, where you're first presented with folders that are from 2016.  (It would be a bit better if reverse sorted by date):
![image](https://user-images.githubusercontent.com/11063618/56700274-4c2ef800-66ae-11e9-9dc4-bf3a05a112fb.png)

 - https://clearlinux.org/downloads
 - https://download.clearlinux.org/releases/

**Comment by dbkinder** [comment]
... and technically, the link for "**previous releases**" takes you to a download area that includes "**future releases**" too (e.g., the button for "latest release" at the top of the page is currently for 28970 but there are many release directories available with numbers higher than 28970)

**Comment by mvincerx** [comment]
@phmccarty , @gtkramer, regarding the last issue that @dbkinder raises, Can we provide any input as to how the CDN directory,[ Index of releases](https://cdn.download.clearlinux.org/releases/), is sorted?

**Comment by phmccarty** [comment]
@mvincerx I will request to fix the sorting of index pages.

**Comment by mvincerx** [comment]
@phmccarty Thanks for looking into this. Please respond here with what you discover.

**Comment by dbkinder** [comment]
Discussion with the devops team uncovers that the current release downloads index infrastructure is changing soon, so they'll not make updates here now.

**Comment by mvincerx** [comment]
@dbkinder Thanks. Please see my recent email. Hopefully, we'll get some clarity internally on the plan.

**Comment by mvincerx** [comment]
"Previous releases" link will move up in downloads page. For details on number indexing, see my recent email.  Closing issue.
