### ISSUE TITLE
dlrs | tcs editorial review

### ISSUE THREAD

**Issue by mvincerx** [clearlinux/clear-linux-documentation#468]
@MCamp859 Will you please do a TCS editorial review of this merged PR? 
https://github.com/clearlinux/clear-linux-documentation/pull/463

Please review and assess whether the Jupyter Notebook could be better integrated in content flow.
Please apply your magic editorial wand to fix formatting, word choice, etc.

**Comment by mvincerx** [comment]
@MCamp859. Can you, by chance, do this today? We're about to have a lot of eyes on this material.

**Comment by MCamp859** [comment]
Will do.
