### ISSUE TITLE
LibreOffice is now a bundle and instruction for installing through Flatpak should probably be deprecated

### ISSUE THREAD

**Issue by bktan8** [clearlinux/clear-linux-documentation#480]
**Describe the error/improvement to an existing document or image**

LibreOffice is now a bundle and installing through Flatpak should probably be deprecated in this document: https://clearlinux.org/documentation/clear-linux/tutorials/flatpak

**Comment by tpleavitt** [comment]
I'd suggest just changing the app to one that we don't include the binary for

**Comment by puneetse** [comment]
Looking at the [popular apps on flathub ](https://flathub.org/apps/collection/popular) -  Steam, Filezilla, vscode seem like good candidates.

**Comment by mvincerx** [comment]
I vote for [Visual Studio Code](https://flathub.org/apps/details/com.visualstudio.code.oss). It's practical and pretty handy for coding.  [FIleZilla ](https://flathub.org/apps/details/org.filezillaproject.Filezilla)is my second choice--for practicality too.

**Comment by mvincerx** [comment]
[Issue 479](https://github.com/clearlinux/clear-linux-documentation/issues/479) will be addressed in PR for this issue. Now, both conditions need to be met to close #480.

**Comment by mvincerx** [comment]
Hey @krisdale. From our discussion last week, please take this and demo FileZilla.

**Comment by tpleavitt** [comment]
Focus on filezilla for now

**Comment by mvincerx** [comment]
@krisdale is working on it.

**Comment by mvincerx** [comment]
Great! It's closed. Thanks, @MCamp859
