### ISSUE TITLE
Recommend adding "desktop-autostart" instead "desktop" bundle to install Flatpak

### ISSUE THREAD

**Issue by bktan8** [clearlinux/clear-linux-documentation#481]
**Describe the error/improvement to an existing document or image**
In this document: https://clearlinux.org/documentation/clear-linux/tutorials/flatpak, it says:

```
Install Flatpak on your host system

Flatpak is included as part of the bundle desktop. To install the application, log in to your user account and enter the following command:

sudo swupd bundle-add desktop
```

I would suggest adding the "desktop-autostart" bundle instead.  This way GDM will start automatically.

**Comment by tpleavitt** [comment]
Good catch!  This tutorial was originally written when xfce was the main desktop (we didn't have desktop-autostart yet!)

**Comment by mvincerx** [comment]
I'll take this and #480. All are related.

**Comment by tpleavitt** [comment]
Need to update the flathub.org website to use desktop-autostart as well

**Comment by mvincerx** [comment]
@krisdale Please look into this for us. 
https://flatpak.org/setup/Clear%20Linux/

**Comment by mvincerx** [comment]
> **Describe the error/improvement to an existing document or image**
> In this document: https://clearlinux.org/documentation/clear-linux/tutorials/flatpak, it says:
> 
> ```
> Install Flatpak on your host system
> 
> Flatpak is included as part of the bundle desktop. To install the application, log in to your user account and enter the following command:
> 
> sudo swupd bundle-add desktop
> ```
> 
> I would suggest adding the "desktop-autostart" bundle instead. This way GDM will start automatically.

A user can just run `sudo swupd bundle-add `flatpak` now, or install it using `desktop`. 
I believe this command should be revised according to the former. 

I agree it would be good to install `desktop-autostart` too, but this is a separate issue. Can you please clarify what you mean by this comment?

**Comment by mvincerx** [comment]
@bktan8. Do you have any thoughts on this?

**Comment by bktan8** [comment]
My rationale for installing `desktop-autostart` instead of `desktop` is that the GUI will start automatically, whereas with the regular `desktop` bundle, you have to manually start it.  `desktop` is a subset of `desktop-autostart` and would make easier for the user instead of trying to figure out to launch the GUI.  Here's the bundle definition of `desktop-autostart`:
`
# [TITLE]: desktop-autostart
# [DESCRIPTION]: Bundle to automatically launch the GUI upon boot.
# [STATUS]: Active
# [CAPABILITIES]:
# [TAGS]: Other
# [MAINTAINER]: Marcos Simental <marcos.simental.magana@intel.com>

include(desktop)

gdm-autostart
gnome-initial-setup
`

If the intent of this doc is just to install Flatpak, there is a `flatpak` bundle available.  To me, `flatpak` kills 1 bird with 1 stone, `desktop` kills 2 birds, whereas `desktop-autostart` kills 3.

**Comment by mvincerx** [comment]
@bktan8. Thanks for sharing your rationale. Sounds like a plan. I'll update the PR.

**Comment by mvincerx** [comment]
@krisdale. Adding you here because you're working on GH-592, which references this Issue.
