### ISSUE TITLE
Correction needed in DKMS document

### ISSUE THREAD

**Issue by bktan8** [clearlinux/clear-linux-documentation#485]
**Describe the error/improvement to an existing document or image**
In the document: https://clearlinux.org/documentation/clear-linux/guides/maintenance/kernel-modules-dkms#kernel-modules-dkms

It says:

```
Out-of-tree kernel modules can be can be manually built and maintained. Out-of-tree kernel modules can also be managed with the Dynamic Kernel Module System (DKMS) on Clear Linux OS using the instructions in this document.
```

The first sentence has 2 instances of "can be can be".  I'm assuming the 2nd "can be" was meant to be "added".

**Comment by MCamp859** [comment]
@bktan8  This text error will be corrected when PR https://github.com/clearlinux/clear-linux-documentation/pull/454 is merged.

**Comment by mvincerx** [comment]
Closed per merge: https://github.com/clearlinux/clear-linux-documentation/pull/454/files
