### ISSUE TITLE
Update VirtualBox Guest Additions

### ISSUE THREAD

**Issue by mvincerx** [clearlinux/clear-linux-documentation#492]
**Describe the error/improvement to an existing document or image**

"Is there a way to fix this easily? The docs explaining how to install the VBox GAs are very bare-bones and seem very incomplete."

CL Forum: https://community.clearlinux.org/t/installation-in-virtualbox-vm-still-problematic/301

CL doc: https://clearlinux.org/documentation/clear-linux/get-started/virtual-machine-install/virtualbox-cl-installer
[Corrected document reference ] 

**Screenshots**
If applicable, add screenshots to help explain the error or unexpected behavior.

**Environment (please complete the following):**

User environment:
VirtualBox 6.0.8 
CL 29400

**Comment by tpleavitt** [comment]
This does need to be updated since we don't walk through the actual process required to add the guest additions.

**Comment by puneetse** [comment]
> This does need to be updated since we don't walk through the actual process required to add the guest additions.

Can you be more specific about what you mean when you say process? There is a section for [Install VirtualBox Linux Guest Additions](https://clearlinux.org/documentation/clear-linux/get-started/virtual-machine-install/virtualbox#install-vb-linux-guest-additions) in the doc.

**Comment by tpleavitt** [comment]
The majority of the doc is on point but when I go to Devices/Insert guest additions CD I have to follow a different process.  I'll rerun the process and let you know what is different

**Comment by mvincerx** [comment]
Closed this issue per closure of GH-493.
