### ISSUE TITLE
Correction needed in "Install VirtualBox Linux Guest Additions"

### ISSUE THREAD

**Issue by busykai** [clearlinux/clear-linux-documentation#495]
**Describe the error/improvement to an existing document or image**
The document recommends running `clr-boot-manager set-kernel` and then `clr-boot-manager update`. However, they should be run the other way around: `update` first and then `set-kernel`. Because update will reset the default kernel to the latest kernel which is most like will be `native`, not `lts`.

**Additional context**
See clearlinux/distribution#733

**Comment by mvincerx** [comment]
This will be addressed in #492.

**Comment by mvincerx** [comment]
Closed this issue per closure of GH-493.
