### ISSUE TITLE
Resolve VirtualBox crash

### ISSUE THREAD

**Issue by mvincerx** [clearlinux/clear-linux-documentation#498]
**Describe the error/improvement to an existing document or image**

**NOTE: Original guide specifies Clear Linux OS as host, whereas user has Windows.**

1. Resolve crash on Linux OS as host: 

Error: "Kernel driver not installed (rc=-1908)

General: 
- Revise Virtual Box to match VB 6.0.8. Include new figures.

2. Resolve system crash, Windows 10 (?)

https://clearlinux.org/documentation/clear-linux/get-started/virtual-machine-install/virtualbox

- Windows: Error occurs: "System acceleration" after selecting storage in VB dialogue. 
- VM crashes 

**Screenshots**
If applicable, add screenshots to help explain the error or unexpected behavior.

**Environment (please complete the following):**
 - Clear Linux OS version: [`cat /usr/lib/os-release`]
 - Third-party tool/software: [version]
 - Command [ [e.g. `sudo -i`]

1.	I installed the latest version of Oracle VirtualBox VM, 6.0.8
2.	I downloaded the most recent version of Clear Linux’s .iso file from the Downloads page (v29450 from the Clear Linux* OS Desktop link)
3.	Using 7zip, I extracted the .iso file
4.	I skipped the step for coverting the .img to a .vdi
5.	I launched VirtualBox, and clicked ‘New’, and tried to set the settings as prescribed, but wasn’t able to select a 64-bit option

![image](https://user-images.githubusercontent.com/37549381/57955862-dfbda800-78ab-11e9-9fa6-bc0dd510cee5.png)

6.	I completed the rest of the creation steps as stated
7.	In the settings tab, I selected ‘Enable I/OAPIC’ and ‘Enable EFI’
8.	Under ‘storage’, I loaded the ISO as a live disk

9.	I got a ‘system acceleration’ error 
![image](https://user-images.githubusercontent.com/37549381/57955890-f6fc9580-78ab-11e9-852c-a87cc766b9c2.png)

10.	I went to system and unselected ‘Enable Vt-x’, and hit ‘OK’
11.	I tried to launch the VM and initially it looked OK, but quickly crashed with the following error 
![image](https://user-images.githubusercontent.com/37549381/57955909-024fc100-78ac-11e9-9c6b-2f03574074fe.png)

12.	I thought maybe there was an issue with my virtualization, and so I double checked that virtualization was enabled via Task Manager. 
![image](https://user-images.githubusercontent.com/37549381/57955923-11cf0a00-78ac-11e9-8c8b-bb192ed103fb.png)

13.	I double checked that Hyper-V was turned off via Windows Features
![image](https://user-images.githubusercontent.com/37549381/57955939-1eebf900-78ac-11e9-8aad-e481f6b998d7.png)
![image](https://user-images.githubusercontent.com/37549381/57955958-29a68e00-78ac-11e9-820a-7b3a99f76f7f.png)

14.	All tutorials and guides online suggest that this is a virtualization problem on my machine, but I can’t identify where the issue is.

**Comment by tpleavitt** [comment]
@mvincerx , is this on an IT Windows machine?

**Comment by mvincerx** [comment]
Answer coming soon. User submitted this.

**Comment by mvincerx** [comment]
I successfully installed CL using clr-24960-live.desktop.iso to a Windows' hosted VirtualBox VM, using VirtualBox 6.0.8.
