### ISSUE TITLE
Document how to increase number of open file descriptors

### ISSUE THREAD

**Issue by puneetse** [clearlinux/clear-linux-documentation#499]
**Do you think Clear Linux documentation needs a new document? Please describe.**
We need a document that describes how to increase the number of open files allowed. Certain applications require more than the default value.

**Should the new document be a guide, a reference, or a tutorial?**
Guide

**Describe or provide examples of similar documents, if possible, from other web sites**
https://community.clearlinux.org/t/increasing-the-maximum-number-of-files-open/331/6
https://community.clearlinux.org/t/how-to-permanent-set-ulimit-n-value/395/2
https://mydbops.wordpress.com/2017/12/10/ulimit-conflict-with-pam-and-systemd

**Additional context**
It should describe the default values, difference between hard and soft limits, system limits vs. systemd limits vs PAM limits, and changing for system-wide or per-user.

**Comment by mvincerx** [comment]
@puneetse Please take the lead on this. Thanks.

**Comment by mvincerx** [comment]
Consider adding to the FAQ.
