### ISSUE TITLE
Multi-boot no longer requires Clear Linux to be installed first

### ISSUE THREAD

**Issue by ttzeng** [clearlinux/clear-linux-documentation#503]
**Describe the error/improvement to an existing document or image**
The step 1 of the multi-boot tutorial no longer valid since installer has been added to the image. For example, the live desktop installer can install Clear Linux to unused partitions.

**Additional context**
The current [multi-boot tutorial](https://clearlinux.org/documentation/clear-linux/tutorials/multi-boot) states:
Install Clear Linux OS **first** with a EFI partition large enough to store the kernels of other operating systems and their initrds, in the case of Linux distributions.

**Comment by bktan8** [comment]
@ttzeng  - Multi-boot doc is still relevant for BIOSes (such as Lenovo) that doesn't show more than 1 EFI partitions.   I have tested multiple Lenovo laptops and even though I was able to install Clear alongside another OS, Clear doesn't show up during POST when you tell it show bootable partitions.

**Comment by mvincerx** [comment]
@bktan8 Are we OK to close this issue? You will also review GH-382, which updates multi-boot doc.

**Comment by bktan8** [comment]
@mvincerx - yes.

**Comment by mvincerx** [comment]
Closed per @bktan8 feedback above. Revisions to multi-boot addressed in GH-382.
