### ISSUE TITLE
Installation failure exit status 35

### ISSUE THREAD

**Issue by wildhevire** [clearlinux/clear-linux-documentation#508]
![Screenshot from 2019-05-23 20-18-30](https://user-images.githubusercontent.com/9078000/58283502-f4aca680-7d97-11e9-9ca2-a8e2e789d36a.png)
I'm doing normal destructive installation with some additional bundles in my system
I can't find what failure code means

**Comment by puneetse** [comment]
Hey @wildhevire. Can you open this issue in the clr-installer repo here: https://github.com/clearlinux/clr-installer/issues instead. It will be better served there. 

It will also help if you can attach a copy of the `clr-installer.log`. It should be in $HOME or /

**Comment by wildhevire** [comment]
Sorry for opening in wrong place, but now it works fine just reboot and try to install it again.
I'm not sure what happen here coz im really doing nothing

**Comment by tpleavitt** [comment]
@wildhevire , could have been a hickup in your connection...sometimes it happens but swupd will try again
