### ISSUE TITLE
VBox installation instructions

### ISSUE THREAD

**Issue by iuvbio** [clearlinux/clear-linux-documentation#510]
The linked download page in the [VBox preconfigured instructions](https://clearlinux.org/documentation/clear-linux/get-started/virtual-machine-install/virtualbox) defaults to a live.iso file **not** a live.img file.

![image](https://user-images.githubusercontent.com/13389526/58358273-85f64880-7e7e-11e9-91ec-49ae03dfe13a.png)

The conversion from iso to vdi works as well, causing a vdi file to be created which always boots into a live environment. Also, on the linked page there is no image listed as "Clear Linux OS live boot image", only "Clear Linux OS Desktop" provides a link to a live installer, which is an iso file.

![image](https://user-images.githubusercontent.com/13389526/58358420-1af94180-7e7f-11e9-8b5f-adafe8a2085d.png)

---
![image](https://user-images.githubusercontent.com/13389526/58358242-63642f80-7e7e-11e9-92ea-9354ec75aa4f.png)

Following the ["manual" install instructions](https://clearlinux.org/documentation/clear-linux/get-started/virtual-machine-install/virtualbox-cl-installer) the machine does **not** boot into a live installer, instead into the root shell described in the other instruction for a pre-configured vdi..

![image](https://user-images.githubusercontent.com/13389526/58358531-922ed580-7e7f-11e9-8734-3d644f5c9a24.png)

Would be good if that could be updated.

**Comment by puneetse** [comment]
@iuvbio sorry for the confusion. We're aware of it and working on unifying the virtualbox instructions. 
In the mean time I suggest using the live-server ISO to boot from and manually installing.

**Comment by mvincerx** [comment]
@iuvbio. If you like, you can follow the draft version in GH-502, where we're using the `live-server` iso.
Thanks for your patience.
