### ISSUE TITLE
Automate the broken links detection in https://clearlinux.org site

### ISSUE THREAD

**Issue by tpleavitt** [clearlinux/clear-linux-documentation#516]
Over time, some broken links in the clearlinux.org site have been reported both on IRC (#clearlinux @ freenode) and in mailing lists.

If we could have a job constantly running to check broken links, we could avoid our users get hit by 404 pages.

Issue copied from CLEAR-1637

**Comment by tpleavitt** [comment]
This will be implemented when new docs site goes online

**Comment by ttzeng** [comment]
I remember Sphinx has a URL validator built-in, that can be used to report broken links in .rst files. I think we can use that mechanism periodically while compiling .rst files in the clear-linux-documentation folder. :)

**Comment by ttzeng** [comment]
I just run the Sphinx ``linkcheck`` builder against the current HEAD ``be3c7f0``, there is no broken link in the except a false alarm.

**Comment by mvincerx** [comment]
@intelkevinputnam will address after site is ready.

**Comment by mvincerx** [comment]
@intelkevinputnam let's confirm that this works. @mvincerx will verify.

**Comment by mvincerx** [comment]
Closed per GH-720.
