### ISSUE TITLE
New guide: Run Clear as a Parallels* guest OS

### ISSUE THREAD

**Issue by tpleavitt** [clearlinux/clear-linux-documentation#518]
New guide requested by Tan, Bun K : Run Clear as a Parallels* guest OS. 

Guide draft already done (on local branch). 

Updated instructions: 

Run Clear Linux as a Parallels guest OS*
Note: Tested against Parallels 14 and Clear 28020

1. Download ISO installer from https://download.clearlinux.org/image/
2. $ gunzip clear-<version>-installer.iso.xz
3. Start Parallels and initialize VM
    1. Go to “File” > “New”
    2. Select “Install Windows or another OS from a DVD or image” (see Figure 1)
    3. Select “Image File” (see Figure 2)
    4. Click “Select a file...”
    5. Select the “clear-<version>-installer.iso” file (see Figure 3)
    6. Click “Continue”
    7. Select “More Linux > Other Linux” from the dropdown (see Figure 4)
    8. Name the VM (see Figure 5)
    9. Click “Create”
    10. Ignore camera and microphone access restriction warnings. (See Figure 6)
4. Go through normal Clear installation process
5. After installation, it will reboot and fail
6. Post configuration to make the VM boot
    1. Stop and shutdown the VM by going to “Actions” > “Stop”
    2. At the Parallels “Control Center,” right-click the VM and select “Configure”
    3. Go to “Hardware” > “Boot Order” (See Figure 7)
    4. Expand “Advanced Settings” and enter “vm.bios.efi=1” under “Boot flags:”
7. Boot the VM
    1. At the Parallels “Control Center,” right-click the VM and select “Start”

**Comment by mvincerx** [comment]
Closed per GH-749.
