### ISSUE TITLE
OVMF fails with ASSERT on kvm

### ISSUE THREAD

**Issue by itsadok** [clearlinux/clear-linux-documentation#521]
My host is ubuntu 19.04. I used OVMF.fd timestamped 18-May-2019 02:08, sha256sum start with `ecac18b7`.
I followed the instructions on the [Run as KVM Guest OS](https://clearlinux.org/documentation/clear-linux/get-started/virtual-machine-install/kvm), and after executing `./start_qemu.sh` the process hangs while taking 100% CPU, and the last line in debug.log is:

    ASSERT /builddir/build/BUILD/edk2-vUDK2018/MdeModulePkg/Core/Dxe/Image/Image.c(1695): Image->Tpl == gEfiCurrentTpl

After some experimenting, I discovered that by copying `OVMF_VARS.fd` and `OVMF_CODE.fd` from `/usr/share/OVMF` into the working directory, I was able to boot successfully. (These files come from [ubuntu's ovmf package](https://packages.ubuntu.com/disco/ovmf)).
I tried the same with `OVMF_VARS.fd` and `OVMF_CODE.fd` from https://cdn.download.clearlinux.org/image/, but got the ASSERT again.

[debug.log](https://github.com/clearlinux/distribution/files/3193901/debug.log)

**Comment by mvincerx** [comment]
> My host is ubuntu 19.04. I used OVMF.fd timestamped 18-May-2019 02:08, sha256sum start with `ecac18b7`.
> I followed the instructions on the [Run as KVM Guest OS](https://clearlinux.org/documentation/clear-linux/get-started/virtual-machine-install/kvm), and after executing `./start_qemu.sh` the process hangs while taking 100% CPU, and the last line in debug.log is: [...]

> [debug.log](https://github.com/clearlinux/distribution/files/3193901/debug.log)

You indicated your "host is Ubuntu..", so we cannot support this use case. I encourage you to adopt Clear Linux* OS as your host. Checkout our [new desktop installer documentation](https://clearlinux.org/documentation/clear-linux/get-started/bare-metal-install-desktop).

**Comment by busykai** [comment]
@mvincerx, installer has nothing to do with the issue in question. Please read carefully the original report. Our [documentation](https://clearlinux.org/documentation/clear-linux/get-started/virtual-machine-install/kvm) *clearly* refers to Ubuntu as the host (and it should).

**Comment by mvincerx** [comment]
I apologize.

**Comment by busykai** [comment]
@mvincerx, no problem at all! :) just making sure we keep track of it. thanks!

**Comment by mvincerx** [comment]
Closed.
