### ISSUE TITLE
INSTALL CLEAR LINUX USING CLR-INSTALLER WITH A CONFIG FILE

### ISSUE THREAD

**Issue by bktan8** [clearlinux/clear-linux-documentation#523]
**Do you think Clear Linux documentation needs a new document? Please describe.**
Need a document on how to install Clear using clr-installer with a config file. See attached PDF.
Target audience: Developer; System Administrator; or Basic User.

**Should the new document be a guide, a reference, or a tutorial?**
Guide.

[INSTALL CLEAR LINUX USING CLR-INSTALLER WITH A CONFIG FILE.pdf](https://github.com/clearlinux/clear-linux-documentation/files/3282330/INSTALL.CLEAR.LINUX.USING.CLR-INSTALLER.WITH.A.CONFIG.FILE.pdf)

**Comment by tpleavitt** [comment]
@MCamp859 , please work with @bktan8 , who has written the procs and needs to convert to .rst

**Comment by mvincerx** [comment]
Close per merge of GH-568.
