### ISSUE TITLE
Corrections to CL Compute Engine guide 

### ISSUE THREAD

**Issue by mvincerx** [clearlinux/clear-linux-documentation#524]
**Describe the error/improvement to an existing document or image**
https://clearlinux.org/documentation/clear-linux/get-started/virtual-machine-install/gce

TCS editorial review. Apply your magic, plus, please: 
- Correct URLs
- Add figure numbers and references to them where appropriate

Note: Use case has been validated.

**Additional context**
Reference previous: GH-505

**Comment by krisdale** [comment]
Resolved with #534
