### ISSUE TITLE
How to query package information from upstream repos

### ISSUE THREAD

**Issue by bktan8** [clearlinux/clear-linux-documentation#527]
**Do you think Clear Linux documentation needs a new document? Please describe.**
Would like to suggest a document (see attached) on how to query package information from the upstream repo.  This is more of a "tip-and-trick" for developers/advanced users.

**Should the new document be a guide, a reference, or a tutorial?**
TBD.  Would be nice to have a "Tips and Tricks" section.  At the very least, it should be a guide.  

[QUERY PACKAGE INFORMATION FROM CLEAR LINUX UPSTREAM REPOS.pdf](https://github.com/clearlinux/clear-linux-documentation/files/3254740/QUERY.PACKAGE.INFORMATION.FROM.CLEAR.LINUX.UPSTREAM.REPOS.pdf)

**Comment by mvincerx** [comment]
Kris, please work with @bktan8 on this. @bktan8 Thanks for this neat tool.  I recommend adding a couple successful console output for 1-2 query commands in the PDF.

**Comment by mvincerx** [comment]
Merged per GH-637
