### ISSUE TITLE
Create documentation for using swupd third party

### ISSUE THREAD

**Issue by tpleavitt** [clearlinux/clear-linux-documentation#528]
**Do you think Clear Linux documentation needs a new document? Please describe.**
Document how to use swupd third party

**Should the new document be a guide, a reference, or a tutorial?**
guide

**Comment by mvincerx** [comment]
In progress per @bktan8 .

**Comment by mvincerx** [comment]
@krisdale. Please note that this is an example of experimental feature.

**Comment by mvincerx** [comment]
@bktan8 will follow up.

**Comment by mvincerx** [comment]
@bktan8 will work with @MCamp859 this week.

**Comment by mvincerx** [comment]
@bktan8 still working on it.

**Comment by mvincerx** [comment]
Still blocked. @bktan8 will follow up swupd engineers.

**Comment by mvincerx** [comment]
Waiting for feedback from engineering.

**Comment by mvincerx** [comment]
@bktan8 please add @bryteise as a reviewer when you submit the PR. Thanks.

**Comment by mvincerx** [comment]
@bktan8 will meet with @mvincerx today.
