### ISSUE TITLE
Update Clear Linux OS image type documentation

### ISSUE THREAD

**Issue by tpleavitt** [clearlinux/clear-linux-documentation#532]
The document https://clearlinux.org/documentation/clear-linux/guides/maintenance/image-types#image-types is out of date and needs to be updated to include the new installer iso images.  I've made a similar request in https://github.com/clearlinux/distribution/issues/865

**Comment by tpleavitt** [comment]
@intelkevinputnam , can you work with @gtkramer and make this a high priority.  He wants to get these updated this week if possible.

**Comment by gtkramer** [comment]
source/clear-linux/guides/maintenance/validate-signatures.rst also needs updated to no longer reference the installer image.

**Comment by gtkramer** [comment]
The following is the tentative list of correct image types that we officially publish and should have listed as image types in our documentation:
* aws
* azure
* azure-docker
* azure-machine-learning
* cloudguest
* gce
* hyperv
* kvm
* legacy-kvm
* live-desktop
* live-server
* pxe
* vmware

**Comment by gtkramer** [comment]
The images link in https://clearlinux.org/documentation/clear-linux/guides/maintenance/image-types#image-types should point to https://clearlinux.org/downloads to avoid redirecting people to our file server.

**Comment by gtkramer** [comment]
https://clearlinux.org/downloads will be updating in the next day or two here to expose the full list of images above, adding aws, pxe, and gce.

**Comment by gtkramer** [comment]
README-IMAGES.html has been removed from the file server in favor of people going to https://clearlinux.org/downloads or visiting the public documentation for image types.

**Comment by gtkramer** [comment]
@bktan8 fyi

**Comment by intelkevinputnam** [comment]
@gtkramer Got it. Working up a PR now.

**Comment by intelkevinputnam** [comment]
PR#548 opened to address this.  https://github.com/clearlinux/clear-linux-documentation/pull/548

**Comment by krisdale** [comment]
Issue resolved with PR #548
