### ISSUE TITLE
How to install and use PHP extensions

### ISSUE THREAD

**Issue by puneetse** [clearlinux/clear-linux-documentation#538]
**Do you think Clear Linux documentation needs a new document? Please describe.**
This topic has come up a few times so it would be nice to have a document for it. The statelessness of CL is probably the most unique part.

**Should the new document be a guide, a reference, or a tutorial?**
guide

**Additional context**
https://community.clearlinux.org/t/how-to-install-php-extension-ext-imagick/298/

**Comment by mvincerx** [comment]
In progress.

**Comment by bd-dean** [comment]
This issue is satisfied with the comments in the forum https://community.clearlinux.org/t/how-to-install-php-extension-ext-imagick/298/ and doesn't need further documentation here.

**Comment by puneetse** [comment]
I'm reopening this based on this complications described here https://community.clearlinux.org/t/php-fpm-is-it-excluded-from-the-stateless-paradigm-and-not-going-to-be-overwritten-by-swupd/1607/17.

An overall PHP document would be good, clarifying the details here https://github.com/clearlinux/clr-man-pages/blob/master/stateless.7.rst#php-fpm and where PHP values can be defined.

**Comment by bd-dean** [comment]
Closed with #869
