### ISSUE TITLE
How to troubleshoot clr-installer failures

### ISSUE THREAD

**Issue by puneetse** [clearlinux/clear-linux-documentation#539]
**Do you think Clear Linux documentation needs a new document? Please describe.**

This could be a new document or added to an existing one. It is frequently asked how to diagnose installer issues, where relevant logs are, what certain codes indicate etc.

**Should the new document be a guide, a reference, or a tutorial?**
guide

**Additional context**
@mdhorn

**Comment by mvincerx** [comment]
This is handled by upcoming features by clr-installer team.
