### ISSUE TITLE
Document iptables firewall and default rulesets

### ISSUE THREAD

**Issue by puneetse** [clearlinux/clear-linux-documentation#541]
**Do you think Clear Linux documentation needs a new document? Please describe.**
Document which firewall CL uses, no FW rules are set by default, and how to save/restore with systemd units. 

This is not unique to Clear Linux. 

**Should the new document be a guide, a reference, or a tutorial?**
guide

**Describe or provide examples of similar documents, if possible, from other web sites**
https://wiki.archlinux.org/index.php/Simple_stateful_firewall
https://fedoraproject.org/wiki/How_to_edit_iptables_rules
https://help.ubuntu.com/community/IptablesHowTo

**Additional context**
https://community.clearlinux.org/t/firewall-packages/734

**Comment by mvincerx** [comment]
Hold until clarity on new firewall packages. See also FAQ doc for now.
