### ISSUE TITLE
Remove or Update Live Beta getting started guide

### ISSUE THREAD

**Issue by mdhorn** [clearlinux/clear-linux-documentation#546]
**Describe the error/improvement to an existing document or image**
The is an outdated getting started guide which is found via search which still references the older live beta image.  Please remove or update.

**Screenshots**
https://clearlinux.org/documentation/clear-linux/get-started/bare-metal-install-beta

**Comment by tpleavitt** [comment]
Thanks for catching that @mdhorn , we'll get it removed asap!

**Comment by tpleavitt** [comment]
@krisdale , can you remove this guide?

**Comment by tpleavitt** [comment]
FYI, it can only be found through the search function, I don't see any specific links to it from the menus or other documents

**Comment by mdhorn** [comment]
@tpleavitt Yeah, I didn't see a direct link but was searching for something and that came up at the top.

**Comment by tpleavitt** [comment]
This has been fixed

**Comment by mdhorn** [comment]
@mdhorn Thanks Tom.
