### ISSUE TITLE
Remove container-host-kvm.img as an image type

### ISSUE THREAD

**Issue by gtkramer** [clearlinux/clear-linux-documentation#554]
**Describe the error/improvement to an existing document or image**
Remove container-host-kvm.img (along with its description mentioning Clear Containers) from the list of image types because it is considered a development image and not a production image.

https://clearlinux.org/documentation/clear-linux/guides/maintenance/image-types

**Screenshots**
N/A

**Environment (please complete the following):**
 - Clear Linux OS version: N/A
 - Third-party tool/software: N/A
 - Command N/A

**Additional context**
N/A

**Comment by krisdale** [comment]
Resolved with PR #555 .
