### ISSUE TITLE
Missing Bundles guide

### ISSUE THREAD

**Issue by jonobacon** [clearlinux/clear-linux-documentation#562]
https://clearlinux.org/documentation/clear-linux/guides/maintenance/mixin is 404ing.

**Comment by tpleavitt** [comment]
Hi @jonobacon , mixin has been been deprecated.  See https://clearlinux.org/documentation/clear-linux/guides 

What brought you to this link for mixin?

**Comment by tpleavitt** [comment]
Expected behavior, closing
