### ISSUE TITLE
launcher.py file in DLRS tutorial is outdated

### ISSUE THREAD

**Issue by crsawyer314** [clearlinux/clear-linux-documentation#563]
The launcher.py file found at https://github.com/clearlinux/dockerfiles/blob/4e976ab8e37cce9dd93fe5de871d0cf4d7c138e0/stacks/dlrs/kubeflow/launcher.py is 7 months old. It looks like Kubeflow has released a more recent version of this file at https://github.com/kubeflow/kubeflow/blob/master/tf-controller-examples/tf-cnn/launcher.py (only 4 months old). We may want to consider replacing our file with the updated version, or just linking to the original repo, since it looks like they're still updating it.

**Comment by DnPlas** [comment]
Hi @crsawyer314, thanks for reporting this. I'll assign this myself and will take a look at it.

**Comment by mvincerx** [comment]
@DnPlas. I'll be opening a new PR on the DLRS tutorial this week--with @bd-dean--to capture this and more feedback, beyond the `launcher.py` file.  @DnPlas I'll add you as a review on the new PR--TBD.

**Comment by bd-dean** [comment]
Created PR #570 to address linking launcher.py.  That PR will be valid if the current location of launcher.py is not changed.

**Comment by DnPlas** [comment]
@crsawyer314 Please note our documentation is using Kubeflow v0.4.0, meaning we should align launcher.py to what they have on such branch and not master/latest or v0.5.0. We will update launcher.py and all needed files as we move to v0.5.0. We can close this issue if everyone agree.

**Comment by mvincerx** [comment]
This is now moot per release of GH-570, in which the requirement was stated for using Kubeflow 0.4.0.
