### ISSUE TITLE
Error to verify the integrity of the Clear Linux OS image

### ISSUE THREAD

**Issue by biapalmeiro** [clearlinux/clear-linux-documentation#567]
There is an extra ./ at the beginning of the following command:
shasum -a512 ./clear-[version number]-[image type].[compression type] | diff ./clear-[version number]-[image type].[compression type]-SHA512SUMS -

At this tutorial:
https://clearlinux.org/documentation/clear-linux/guides/maintenance/download-verify-decompress-mac#verify-mac

OS: MacOS Majave 10.14.5

**Comment by mvincerx** [comment]
I don't see an extra `./` at the beginning of the command. I just downloaded the latest live-desktop, 30140, and its corresponding SHA512SUMS file, and it worked fine.  I'm running MacOS High Sierra, but that shouldn't make a difference.  Are you sure you included the final "-" at the end of the command?

**Comment by mvincerx** [comment]
@bd-dean please test.

**Comment by bd-dean** [comment]
Ran twice, once with the ./ and once without.  Removing the ./ from the command results in no output from shasum, which is what the tutorial states is a "match".  Recommend we remove ./ from the command in both places it exists in this section of the tutorial. 

Output 
mac01:Downloads #  shasum -a512 ./clear-30210-aws.img.xz | diff ./clear-30210-aws.img.xz-SHA512SUMS -
1c1
< 6bc4f0c3fa878e21c7d7bffbe8fad9ed09c347bee1a8e0c010e5b61ea27b74f1e224210b4175df39cd707bdea81fd8a6d76bdd2c1d564dd4b9acc29290cd6505  clear-30210-aws.img.xz
---
> 6bc4f0c3fa878e21c7d7bffbe8fad9ed09c347bee1a8e0c010e5b61ea27b74f1e224210b4175df39cd707bdea81fd8a6d76bdd2c1d564dd4b9acc29290cd6505  ./clear-30210-aws.img.xz
mac01:Downloads #  shasum -a512 clear-30210-aws.img.xz | diff clear-30210-aws.img.xz-SHA512SUMS -
mac01:Downloads #

**Comment by bktan8** [comment]
I second @bd-dean's recommendation.

**Comment by bktan8** [comment]
@MCamp859 - Can you please create a quick PR for this, remove the 2 "./" and I'll do final review?   
The new command code-block should say:

shasum -a512 clear-[version number]-[image type].[compression type] | diff clear-[version number]-[image type].[compression type]-SHA512SUMS -

**Comment by mvincerx** [comment]
> Ran twice, once with the ./ and once without. Removing the ./ from the command results in no output from shasum, which is what the tutorial states is a "match". Recommend we remove ./ from the command in both places it exists in this section of the tutorial.
> 
> ## Output
> mac01:Downloads # shasum -a512 ./clear-30210-aws.img.xz | diff ./clear-30210-aws.img.xz-SHA512SUMS -
> 1c1
> < 6bc4f0c3fa878e21c7d7bffbe8fad9ed09c347bee1a8e0c010e5b61ea27b74f1e224210b4175df39cd707bdea81fd8a6d76bdd2c1d564dd4b9acc29290cd6505 clear-30210-aws.img.xz
> > 6bc4f0c3fa878e21c7d7bffbe8fad9ed09c347bee1a8e0c010e5b61ea27b74f1e224210b4175df39cd707bdea81fd8a6d76bdd2c1d564dd4b9acc29290cd6505  ./clear-30210-aws.img.xz
> > mac01:Downloads #  shasum -a512 clear-30210-aws.img.xz | diff clear-30210-aws.img.xz-SHA512SUMS -
> > mac01:Downloads #

Agreed on @bd-dean comments. @MCamp859 please let me know if you have questions.

**Comment by mvincerx** [comment]
Closed per GH-602.
