### ISSUE TITLE
Remove ksonnet from  dlrs tutorials

### ISSUE THREAD

**Issue by bd-dean** [clearlinux/clear-linux-documentation#572]
The DLRS tutorial describes using ksonnet to manage deployments.  ksonnet is deprecated and no new work is being done on it.  Ksonnet should be removed from the tutorial and replaced with an alternative. 

**Additional context**
The team behind ksonnet is stepping back from the project. As a result, work on ksonnet will end and the GitHub repositories will be archived.

**Comment by mvincerx** [comment]
@bd-dean will review and advise. Thanks.

**Comment by mvincerx** [comment]
Defer due to security issues until Sept..

**Comment by mvincerx** [comment]
Blocked.

**Comment by mvincerx** [comment]
@bd-dean working on this WW33.

**Comment by mvincerx** [comment]
Closed per release of GH-808.
