### ISSUE TITLE
Installer instructions could be more clear and descriptive

### ISSUE THREAD

**Issue by ebrent8** [clearlinux/clear-linux-documentation#577]
**On the Clear Linux installer header "Launch the Clear Linux OS installer" on this page:**
[https://clearlinux.org/documentation/clear-linux/get-started/bare-metal-install-desktop](https://clearlinux.org/documentation/clear-linux/get-started/bare-metal-install-desktop)

**Problem Description**
The steps below that header and screenshot could be much clearer.

Step 2 : should describe which icon exactly the user should be clicking - "The Clear Linux penguin icon"
Figure 3 : should show an arrow pointing to the correct icon.  Currently, that screenshot shows the wifi panel open (top right) and the Software app icon description alt text showing.  That's weird.  In my opinion, the wifi menu should be closed, don't show the software menu text and have an arrow pointing to the correct icon that you want the user to click.  Fortunately, I have created that for you below.

**Screenshots**
Fixed screenshot with new correct arrow attached here:
![iso-home-installer-arrow](https://user-images.githubusercontent.com/18618930/60360906-aa6ba600-9991-11e9-82ef-b718bc4378f9.png)

**Environment**
 - website documentation,  URL above.

**Comment by tpleavitt** [comment]
Great feedback!  We'll look into it

**Comment by mvincerx** [comment]
@ebrent8 Thanks for the feedback.
