### ISSUE TITLE
Images not rendering properly on new pages

### ISSUE THREAD

**Issue by puneetse** [clearlinux/clear-linux-documentation#578]
**Describe the error/improvement to an existing document or image**
Provide a clear and concise description of the error or proposed improvement.

Images on the stateless page are not rendering: https://clearlinux.org/documentation/clear-linux/concepts/stateless 

The relative image path reference in GH is correct and renders: 
https://github.com/clearlinux/clear-linux-documentation/blob/master/source/clear-linux/concepts/stateless.rst

**Comment by puneetse** [comment]
The same issue for the recently published debug document:
https://clearlinux.org/documentation/clear-linux/guides/tooling/debug
https://github.com/clearlinux/clear-linux-documentation/blob/master/source/clear-linux/guides/tooling/debug.rst

**Comment by mvincerx** [comment]
I filed a ticket on the bug Thursday for error in `debug.rst` and another ticket Friday 28 June on `stateless.rst`.  I'll keep you posted on the status of these tickets.

**Comment by mvincerx** [comment]
Fixed.
