### ISSUE TITLE
Clear logo not fully showing

### ISSUE THREAD

**Issue by crsawyer314** [clearlinux/clear-linux-documentation#583]
**Describe the error/improvement to an existing document or image**
Clear Linux logo not fully showing when in full screen or split-screen in Firefox on Ubuntu 18.04.2 LTS.

**Screenshots**
![Screenshot from 2019-07-01 13-03-51](https://user-images.githubusercontent.com/39068473/60463554-27508700-9c01-11e9-94bb-4ee89c78f6c8.png)
![Screenshot from 2019-07-01 13-00-00](https://user-images.githubusercontent.com/39068473/60463560-2cadd180-9c01-11e9-9fd7-4bc75590dcc6.png)

**Environment (please complete the following):**
 - Clear Linux website (any page)
- Mozilla Firefox 67.0.4 (64-bit)
 - Ubuntu 18.04.2 LTS

**Comment by tpleavitt** [comment]
@mvincerx , this is actually a website issue so if you could include it as part of your items you're tracking with the site...thanks!

**Comment by mvincerx** [comment]
@krisdale will investigate. Thanks.

**Comment by mvincerx** [comment]
Please leave open until Web support resolves.

**Comment by mvincerx** [comment]
Website issue. Closing.
