### ISSUE TITLE
nvidia drivers tutorial - NVIDIA driver is not loaded

### ISSUE THREAD

**Issue by Akiyamka** [clearlinux/clear-linux-documentation#587]
**Describe the error/improvement to an existing document or image**
After complete all steps in fresh Clear Linux installation nvidia drivers not loaded.
Seems to have forgotten a some step

Current state after install and reboot:
```bash
➜ lspci | grep NVIDIA
01:00.0 3D controller: NVIDIA Corporation GP108M [GeForce MX150] (rev a1)

➜ lspci | grep Graphics
00:02.0 VGA compatible controller: Intel Corporation UHD Graphics 620 (rev 07)

➜ sudo cat /etc/modprobe.d/nvidia-disable-nouveau.conf
blacklist nouveau
options nouveau modeset=0

➜  glxinfo|egrep "OpenGL vendor|OpenGL renderer*"
OpenGL vendor string: Intel Open Source Technology Center
OpenGL renderer string: Mesa DRI Intel(R) UHD Graphics 620 (Kabylake GT2) 

➜ nvidia-settings
ERROR: NVIDIA driver is not loaded

➜ lspci -vnnn | perl -lne 'print if /^\d+\:.+(\[\S+\:\S+\])/' | grep VGA
00:02.0 VGA compatible controller [0300]: Intel Corporation UHD Graphics 620 [8086:5917] (rev 07) (prog-if 00 [VGA controller])
00:13.0 Non-VGA unclassified device [0000]: Intel Corporation Sunrise Point-LP Integrated Sensor Hub [8086:9d35] (rev 21)

➜ nvidia-smi -a
NVIDIA-SMI has failed because it couldn't communicate with the NVIDIA driver. Make sure that the latest NVIDIA driver is installed and running.

➜ lsmod | grep ^nvidia
nvidia_drm             45056  0
nvidia_modeset       1114112  1 nvidia_drm
nvidia              18784256  1 nvidia_modeset
nvidiafb               53248  0
```

**Environment (please complete the following):**
 - Clear Linux OS version: 
```
NAME="Clear Linux OS"
VERSION=1
ID=clear-linux-os
ID_LIKE=clear-linux-os
VERSION_ID=30140
PRETTY_NAME="Clear Linux OS"
ANSI_COLOR="1;35"
HOME_URL="https://clearlinux.org"
SUPPORT_URL="https://clearlinux.org"
BUG_REPORT_URL="mailto:dev@lists.clearlinux.org"
PRIVACY_POLICY_URL="http://www.intel.com/privacy"
```
 - Third-party tool/software:
```
NVIDIA-Linux-x86_64-430.26            
```

**Comment by puneetse** [comment]
It looks like the driver is loaded but maybe the hardware isn't being used. 

What's the model of laptop you're using? If it has a hybrid/switchable graphics (NVIDIA Optimus), you may need to force it to use the NVIDIA device and getting it working on Linux has known challenges. A first troubleshooting step would be to try disabling the Intel graphics card completely.

You might get better support from the community on the fourms for this one. We have some NVIDIA users there that are helpful :)

https://wiki.archlinux.org/index.php/NVIDIA_Optimus

https://community.clearlinux.org/t/bash-scripts-to-automate-installation-of-nvidia-proprietary-driver/368/19?u=puneetse

**Comment by Akiyamka** [comment]
@puneetse 
Thank you for your links! After some research I came to understand that only one nvidia card and two cards in one laptop it's are quite different things. As I understand it, one of the easiest ways is switching manually between cards using `prime` or `nvidia-xrun`. Unfortunately, I have not yet found a way to install `nvidia-xrun`. Can I use [guides for fedora](https://copr.fedorainfracloud.org/coprs/ekultails/nvidia-xrun/)? In other words - whether clear linux is Fedora-like distro in this case?

**Comment by mvincerx** [comment]
@puneetse will follow up. Thanks.

**Comment by puneetse** [comment]
@Akiyamka you would have to compile and install those components manually. The Fedora guide you linked likely won't work since it is using parts that conflict with Clear Linux, like GRUB and DNF.

If you have trouble manually building and installing, please post on the forums where the community can help.
