### ISSUE TITLE
Specify to select UEFI USB boot option in boot menu for installation guide

### ISSUE THREAD

**Issue by mrkz** [clearlinux/clear-linux-documentation#590]
Probably a note for step 3 in https://clearlinux.org/documentation/clear-linux/get-started/bare-metal-install-desktop#install-from-live-image

Some HW may list  UEFI and non-UEFI entries USB boot entries. Selecting non-UEFI may lead to the following bug report:

The answer was in the boot sequence options in the bios 
Once the usb stick was in , there were 2 options in the boot sequence:
-- usb sansdisk usb
-- **uefi sandisk usb**

Prioritizing the second option did the job, I could properly boot the iso.

**One thing important to notice:**  the initial menu with the 5 seconds timer, is looking much different when you try to boot the USB from one method or the other.  
With the failing method, the menu has no apparent other option and is framed with a blue background. when it fails , the whole log has a greenish background to it.
With the successful method, the menu has 2 options, and is a blank light grey on black with no frame around, just highlighting of the current option.

You might want to document that.

Still, I gotta say, it's a first, I never had to meddle with the bios for any other distro I've ever installed or tried. And I tried a lot, I'm of the hopper kind, Fedora 30 and openMandriva lx4 lately . 
Even if I stuck with Mint for 1 year, then Manjaro for 2 years, then had to go back to windows to facilitate interactions with Office365, VStudio and Azure, for work.

The problem here might have something to do with the dogmatic and weird way you load the microcode updates (late) (see #52)

You should not require that kind of meddling from end users. A live iso should not require a specific bios setting. Never ever. It should go smoothly, whatever the type of usb boot.

Clearlinux is noticeably promising, in terms of perceived speed , performance, footprint.
And i'm still curious about giving it its full power with an install on a spare SSD. But I do wonder about a grub mulitboot, for instance, with the kind of initialization you have chosen.

_Originally posted by @akamarvin in https://github.com/clearlinux/distribution/issues/930#issuecomment-504699982_

**Comment by mvincerx** [comment]
@mvincerx and @bd-dean will work on it.
