### ISSUE TITLE
Relocate openssh-server to guides/network

### ISSUE THREAD

**Issue by mvincerx** [clearlinux/clear-linux-documentation#664]
**Describe the error/improvement to an existing document or image**
Move openssh-server from:
https://clearlinux.org/documentation/clear-linux/reference/bundles/openssh-server
to:
https://clearlinux.org/documentation/clear-linux/guides/network/openssh-server

Revise title of doc to better identify use-case.

**Comment by mvincerx** [comment]
Hey @MCamp859. Please let me know if you have bandwidth for this. We can discuss Thurs. am.

**Comment by MCamp859** [comment]
@mvincerx  I can do this next Tuesday, is that too late?

**Comment by mvincerx** [comment]
That works fine. Thanks for your quick response.

**Comment by MCamp859** [comment]
Closed by #677
