### ISSUE TITLE
Swupd guide has command output in a code block which is confusing

### ISSUE THREAD

**Issue by eadamsintel** [clearlinux/clear-linux-documentation#665]
If you go to https://clearlinux.org/documentation/clear-linux/guides/maintenance/swupd-guide and look at Step 1 and Step 2 you see that the output of a command is in a code block and has a copy icon next to it. I don't see why anyone would copy the output and it looks like it might be code to run.

**Screenshots**
If you look the output "Enabled" and all the text after "Warning:" is the output of a command but looks like something you would copy into a bash shell. 

![image](https://user-images.githubusercontent.com/25207372/61832938-a499a100-ae27-11e9-9f6b-722a8bbd9e6b.png)

**Comment by mvincerx** [comment]
I think we can solve this by inserting "output" after the first command.

**Comment by mvincerx** [comment]
FYI @eadamsintel. @DougTW fixed this. Going forward, we're working on an improved solution for console output. More details in our next Docs meeting.
