### ISSUE TITLE
Update Hyper-V install documentation 

### ISSUE THREAD

**Issue by puneetse** [clearlinux/clear-linux-documentation#670]
**Describe the error/improvement to an existing document or image**
The Hyper-V getting started document could be more comprehensive, as pointed out in https://github.com/clearlinux/distribution/issues/1059

It is also lacking screenshots compared to our other getting started documents

**Additional context**
https://clearlinux.org/documentation/clear-linux/get-started/virtual-machine-install/hyper-v

**Comment by mvincerx** [comment]
@puneetse working on this WW33.
