### ISSUE TITLE
Broken link in blog

### ISSUE THREAD

**Issue by avemilia** [clearlinux/clear-linux-documentation#672]
https://clearlinux.org/news-blogs/where-etcfstab-clear-linux contains a broken link to "stateless OS architecture". It should point to https://clearlinux.org/documentation/clear-linux/concepts/stateless

**Comment by mrkz** [comment]
Hello @avemilia, first of all, thanks for reaching out and report this issue :tada: 

I transferred your report to the clear-linux-documentation repository, where it will be handled properly.

**Comment by mvincerx** [comment]
I corrected the broken link. Thanks, @avemilia.  We're currently reorganizing many docs.
