### ISSUE TITLE
How do I build the new YAML-defined images?

### ISSUE THREAD

**Issue by m1kc** [clearlinux/clear-linux-documentation#682]
Hi there!

I'm trying out the ister.py tool and right now I just try to recreate different upstream images using [the guide](https://clearlinux.org/documentation/clear-linux/guides/maintenance/ister#recreate-an-upstream-image). And I've ran into a problem: some [image configs](https://cdn.download.clearlinux.org/releases/29700/clear/config/image/) are not in the ister JSON format - instead, they use YAML.

[Readme](https://cdn.download.clearlinux.org/releases/29700/clear/config/image/00ReadMe.html) says that this format is used by clr-installer which is intended to supersede ister. Still, it's not clear to me how do I use clr-installer to create ISO (or raw) images - all the docs I've found only describe using it for automated installs, which is not exactly what I want.

Could someone point me in the right direction here?

**Comment by mvincerx** [comment]
@bktan8 please review and advise us long term.

**Comment by puneetse** [comment]
@m1kc Take a look at https://github.com/clearlinux/clr-installer#install-installing-the-installer as well.

**Comment by mvincerx** [comment]
Thanks, @puneetse. FYI: @mdhorn.

**Comment by mdhorn** [comment]
The current images are only generated with clr-installer and their associated YAML files.
For each published image:
https://cdn.download.clearlinux.org/current/
There is a matching YAML file:
https://cdn.download.clearlinux.org/current/config/image/

The basic syntax is clr-installer -c <yamlfile>
Note that most of the image have pre or post install hooks that would also need to be downloaded from:
https://cdn.download.clearlinux.org/current/config/image/

**Comment by m1kc** [comment]
That did the trick. Thanks! :+1:
