### ISSUE TITLE
Installing Broadcom Wireless Drivers Documentation

### ISSUE THREAD

**Issue by miguelinux** [clearlinux/clear-linux-documentation#684]
Many users asked on how to set up Broadcom wireless drivers.

As an example: https://github.com/clearlinux/distribution/issues/1064

There @lebensterben point it out the following direction
https://askubuntu.com/questions/55868/installing-broadcom-wireless-drivers/60395#60395

**Comment by mvincerx** [comment]
@puneetse, Can you take on this issue?

**Comment by puneetse** [comment]
If we determine this needs special addressing in the Clear Linux documentation, https://github.com/clearlinux/clear-linux-documentation/pull/824 is something that can be used as a building block.

**Comment by mvincerx** [comment]
@bd-dean please check in with @puneetse

**Comment by mvincerx** [comment]
Please a link to the Forum thread.
