### ISSUE TITLE
autospec: documentation website has broken link

### ISSUE THREAD

**Issue by mdhorn** [clearlinux/clear-linux-documentation#686]
**Describe the error/improvement to an existing document or image**
The top level documentation page has a broken link under "Documentation Highlights", the first option of autospec. Clicking this link results in a 404 error.

**Comment by mdhorn** [comment]
https://clearlinux.org/documentation

Broken Link:
https://clearlinux.org/documentation/clear-linux/guides/maintenance/autospec

**Comment by mvincerx** [comment]
Friday 2 August I filed an issue on this with Web team. Monitoring. Web team owns, not a docs issue.

**Comment by mvincerx** [comment]
Fixed per recent edits: https://clearlinux.org/documentation
