### ISSUE TITLE
swupd: documentation website has broken link

### ISSUE THREAD

**Issue by mdhorn** [clearlinux/clear-linux-documentation#687]
**Describe the error/improvement to an existing document or image**
The top level documentation page has a broken link under "Quick Links", the second option of swupd. Clicking this link results in a 404 error.

https://clearlinux.org/documentation

Broken Link:
https://clearlinux.org/documentation/clear-linux/guides/maintenance/swupd-guide

**Comment by mvincerx** [comment]
Friday 2 August I filed an issue on this with Web team. Monitoring.

**Comment by mvincerx** [comment]
Fixed per recent edits: https://clearlinux.org/documentation
