### ISSUE TITLE
Tidying the tutorial section 

### ISSUE THREAD

**Issue by puneetse** [clearlinux/clear-linux-documentation#688]
**Describe the error/improvement to an existing document or image**
Looking at the tutorials section of the website, the titles of the documents are hard to skim through because of the verbosity of verb-phrases and use of "Clear Linux OS" frequently in the titles.

In most cases, the verbs and "on Clear Linux* OS" is implied by the context and location.

This is particularly noticeable in the side navigation or tutorials landing page: https://clearlinux.org/documentation/clear-linux/tutorials#tutorials

Is it possible to have a "short" title for navigation and longer title for the page?

This is a proposal that I think would be tidier:

```
- Apache Hadoop*
- Apache* Spark* 
- Docker* 
- Flatpak*  
- Kubernetes*
- Kubernetes* Best Practices 
- Kata Containers*
- NVIDIA* Drivers
- NVIDIA* CUDA Toolkit
- Redis*
- YubiKey* Support
- Proxy configuration
- Function Multi-Version patch generator
- Samba* as a host 
- Samba* as a client
- TensorFlow* machine learning 
- WordPress*
```

These two seem better off renamed under a "cloud" section under "Getting Started":
```
- Clear Linux* OS on Microsoft Azure
- Clear Linux* OS on Amazon Web Services*
```

Can this be dropped from the documentation? I think the audience for this is dwindling if not non-existent and doesn't add unique value compared to the [upstream documentation](https://github.com/kata-containers/documentation/blob/master/Upgrading.md#upgrade-from-clear-containers )
```
- Migrate Clear Containers to Kata Containers*
```

**Comment by mvincerx** [comment]
@intelkevinputnam will work on this. Cheers.
