### ISSUE TITLE
Tables are not displayed correctly on small screens

### ISSUE THREAD

**Issue by lebensterben** [clearlinux/clear-linux-documentation#689]
![](https://sjc1.discourse-cdn.com/business4/uploads/clearlinux/original/1X/2bcd210ce7adb9b46a160679c4beebff4d8f1734.jpeg)

The screenshot is taken from this https://clearlinux.org/documentation/clear-linux/guides/tooling/mixer

And it also appears here https://clearlinux.org/documentation/clear-linux/reference/bundles#bundles

**Comment by mvincerx** [comment]
@lebensterben, Thanks for pointing this out. We're working on this. Look for updates in the near future.

**Comment by mvincerx** [comment]
@mvincerx  FYI.

**Comment by lebensterben** [comment]
>@mvincerx  FYI.

@mvincerx things are working fine now.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by mvincerx** [comment]
Yes. Thanks.
