### ISSUE TITLE
Download `.flatpakref` when `GET` is clicked on Clear Linux Store

### ISSUE THREAD

**Issue by lebensterben** [clearlinux/clear-linux-documentation#690]
In [Clear Linux* Store](https://clearlinux.org/software), when you click the GET button, a floating window pops up tells you how to install it in command line.

A more user-friendly approach is to download the corresponding .flatpakref file like the official flathub, this file can be opened by gnome-software directly.

**Comment by mvincerx** [comment]
@lebensterben I've filed an issue with our Web team, making your request to them.  Closing here because this is outside the scope of documentation.
