### ISSUE TITLE
Too many contributors shown on main page

### ISSUE THREAD

**Issue by lsandoval** [clearlinux/clear-linux-documentation#70]
CLR main page [1] shows more  1.6k contributors (1688). This is too much and the number needs to be double check.

[1] https://clearlinux.org/

**Comment by matthewrsj** [comment]
I agree this number seems extremely high.

**Comment by rcaballeromx** [comment]
I suspect that we are aggregating contributors from all the CL repositories. Admittedly, most of them will be duplicates. I'll investigate and report back.

**Comment by iphutch** [comment]
Yes, I have been informed that this is precisely what we are doing. I will see what can be done to remove duplicates for this statistic.

**Comment by iphutch** [comment]
Duplicates are no longer included in the number of contributors shown on the CLR main page.
