### ISSUE TITLE
show latest image number when fetching an image

### ISSUE THREAD

**Issue by lsandoval** [clearlinux/clear-linux-documentation#71]
This is a feature, not a bug. There are several places on the documentation that the user is asked to download a image from [1] and then unxz it. IMO, it would be great if the fetch step is also shown as  a wget command including the full url of the most recent image, this way we make it easier for the user and avoid wrong image selection from user.

For example, on the kvm steps:

 1. Download the latest pre-built Clear Linux KVM image file from the image directory. Look for clear-<version>-kvm.img.xz.

  **wget https://download.clearlinux.org/image/clear-19720-kvm.img.xz  <-- this is the new piece of text that needs to be dynamically populated**

[1] https://download.clearlinux.org/image/

**Comment by lsandoval** [comment]
Perhaps the title needs to change, but we should include full command lines when downloading stuff, like OVMF.fd or the start_qemu.sh. Leaving the title as it is for the moment.

**Comment by bktan8** [comment]
@lsandoval  - The "image" directory in https://download.clearlinux.org/image always has the latest.  there aren't multiple versions.  

That said, we can add a command-line code-block to each one of the document where we ask the user to download the latest.  It will download the latest.  @Michael-Vincerra - Here are the changes to make:

1. On https://clearlinux.org/documentation/clear-linux/get-started/bare-metal-install

“Download the latest Clear Linux installer image
Get the latest Clear Linux installer image from the image directory. Look for the clear-[version number]-installer.img.xz file. Once you have downloaded the image, verify and uncompress the file.”
 
Add a code-block:: bash
$ curl -O  https://download.clearlinux.org/image/clear-$(curl https://download.clearlinux.org/latest)-installer.img.xz
 
2. On https://clearlinux.org/documentation/clear-linux/get-started/virtual-machine-install/kvm
“Download and launch the virtual machine
1.   Download the latest pre-built Clear Linux KVM image file from the image directory. Look for clear-<version>-kvm.img.xz.”
 
Add a code-block:: bash
$ curl -O  https://download.clearlinux.org/image/clear-$(curl https://download.clearlinux.org/latest)-kvm.img.xz
 
3. On https://clearlinux.org/documentation/clear-linux/get-started/virtual-machine-install/virtualbox
“Create a virtual machine in VirtualBox
1.    Download the latest live version (clear-XXXX-live.img.xz) from https://download.clearlinux.org/image/ .”
Add a code-block:: bash
$ curl -O  https://download.clearlinux.org/image/clear-$(curl https://download.clearlinux.org/latest)-live.img.xz
 
4. On https://clearlinux.org/documentation/clear-linux/get-started/virtual-machine-install/vmware-esxi-preconfigured-cl-image and https://clearlinux.org/documentation/clear-linux/get-started/virtual-machine-install/vmw-player-preconf 
“Download the latest Clear Linux VMware image
Get the latest Clear Linux VMware image from the image repository. Look for clear-[version number]-vmware.vmdk.xz.
“
Add a code-block:: bash
$ curl -O  https://download.clearlinux.org/image/clear-$(curl https://download.clearlinux.org/latest)-vmware-vmdk.xz

**Comment by Michael-Vincerra** [comment]
Will do so as soon as we meet to resolve minor issues in commands.

**Comment by Michael-Vincerra** [comment]
We've added the curl command in these URLs. This issue is closed.
