### ISSUE TITLE
404 Error for bar metal install tutorial

### ISSUE THREAD

**Issue by biapalmeiro** [clearlinux/clear-linux-documentation#724]
The following link is returning 404 error:
https://clearlinux.org/documentation/clear-linux/get-started/bare-metal-install

Google search:
https://www.google.com/search?q=how+to+boot+clear+linux&oq=how+to+boot+clear+linux&aqs=chrome..69i57j33l5.7765j0j7&sourceid=chrome&ie=UTF-8

<img width="816" alt="Screen Shot 2019-08-12 at 1 53 52 PM" src="https://user-images.githubusercontent.com/5597786/62897892-00f62f00-bd09-11e9-8439-8e27231e8173.png">

Chrome at MacOS Mojave 10.14.6

**Comment by krisdale** [comment]
A redirect has been set up (301) to direct to the correct location for this content.
