### ISSUE TITLE
Revise VNC remote connection documentation

### ISSUE THREAD

**Issue by puneetse** [clearlinux/clear-linux-documentation#731]
**Describe the error/improvement to an existing document or image**
The current VNC document is one of the longest pages we have and is one of the slowest loading pages in documentation. 

The content is very comprehensive, which is good, but there are some tweaks that could improve it:

- Redo screenshots to be consistently sized and optimized for web. Even the current ones can be compressed ~54%.

- Consider splitting content between VNC-server and VNC-client documents, similar to the Samba docs.

- Use `sudo`-prefixed commands to be consistent with the other docs

- Remove prompt prefix inside codeblocks to be consistent with the other docs

- Use text for console output w/ highlighting instead of screenshots of console

**Additional context**
https://docs.01.org/clearlinux/latest/guides/network/vnc.html

**Comment by mvincerx** [comment]
Closed per GH-900. Regarding image sizes, all figures here are approximately 51 KB or less. So if load time is a concern, please test and file a new Issue that is more general.
