### ISSUE TITLE
bundles: Create a "status" tag and show its value

### ISSUE THREAD

**Issue by mvincerx** [clearlinux/clear-linux-documentation#747]
**Describe the error/improvement to an existing document or image**
Provide a clear and concise description of the error or proposed improvement.

In response to @ketonik and @phmccarty, revise `bundle_lister.py` script to: 
- Capture current status for each bundle here: 
https://docs.01.org/clearlinux/latest/reference/bundles/bundles.html
- If a bundle status is "Pending-Delete," color text red for warning to users

Reference Clear Linux Forums: 
https://community.clearlinux.org/t/site-updates-addressing-issues/949/24

**Comment by mvincerx** [comment]
Revised functionality of [available bundles page](https://docs.01.org/clearlinux/latest/reference/bundles/bundles.html) published today, 08-28-19. Cross-referenced on forum.

**Comment by ketonik** [comment]
Looks perfect, fantastic work guys.

**Comment by mvincerx** [comment]
Thank you.
