### ISSUE TITLE
Monitor 404 returned by TensorFlow Benchmarks links in dlrs.rst

### ISSUE THREAD

**Issue by mvincerx** [clearlinux/clear-linux-documentation#767]
In [DLRS tutorial section](https://docs.01.org/clearlinux/latest/tutorials/dlrs.html#tensorflow-single-and-multi-node-benchmarks)  `linkchecker.py()` found a 404 for  embedded URL
[TensorFlow Benchmarks](https://www.tensorflow.org/guide/performance/benchmarks).

Monitor 404 during WW37. tensorflow.org may resolve this issue. Otherwise, CL docs can remove link.

**Comment by intelkevinputnam** [comment]
@bd-dean Looks like the benchmark results at https://www.tensorflow.org/guide/performance/benchmarks have gone away. And google isn't turning up that page anymore either when I search for "tensorflow benchmarks"

Does it make sense to link to their github page instead: https://github.com/tensorflow/benchmarks?
