### ISSUE TITLE
https://docs.01.org/clearlinux/latest/guides/maintenance/assign-static-ip.html shows 404 error

### ISSUE THREAD

**Issue by keerockl** [clearlinux/clear-linux-documentation#780]
https://docs.01.org/clearlinux/latest/guides/maintenance/assign-static-ip.html shows 404 error

**Screenshots**
![image](https://user-images.githubusercontent.com/18294336/64722961-695d3b00-d484-11e9-833d-e3746f5be2ce.png)

**Environment (please complete the following):**

**Additional context**

Please redirect to https://docs.01.org/clearlinux/latest/guides/network/assign-static-ip.html

**Comment by krisdale** [comment]
A 301 redirect has been set up for the page to point it to the new location.
