### ISSUE TITLE
Improvements for create a bootable USB drive on Linux

### ISSUE THREAD

**Issue by puneetse** [clearlinux/clear-linux-documentation#796]
**Describe the error/improvement to an existing document or image**
https://docs.01.org/clearlinux/latest/get-started/bootable-usb.html#bootable-usb-linux

- Explicitly link to https://docs.01.org/clearlinux/latest/guides/maintenance/download-verify-decompress.html#decompress-the-cl-image early in section to make it clear a prerequisite is to decompress after downloading. Currently, the link just says "Verify the integrity of..."
- Highlight output in step 4 to show the USB driver and make it easier to see the targeted device
- Commands in step 5 and 6 should be prefixed with `sudo` for consistency
- Condense step 5 into one command `sudo umount /dev/sdd*` to make sure all partitions get unmounted.
- Add the extension `*.iso` in the command to affirm the decompressed needs to be passed.

**Comment by puneetse** [comment]
Relevant topic for the last bullet: https://github.com/clearlinux/distribution/issues/1239

**Comment by tpleavitt** [comment]
@mvincerx can you check to see if this PR has been merged?  If so, please close

**Comment by mvincerx** [comment]
Closing per GH-842. 
The link to `download-verify-decompress.html` is embedded in the 2nd bullet of 3rd section:
"Verify the integrity of the Clear Linux OS image on Linux."

> * Explicitly link to https://docs.01.org/clearlinux/latest/guides/maintenance/download-verify-decompress.html#decompress-the-cl-image early in section to make it clear a prerequisite is to decompress after downloading. Currently, the link just says "Verify the integrity of..."
