### ISSUE TITLE
Tutorial on updating an existing autospec package

### ISSUE THREAD

**Issue by pdxjohnny** [clearlinux/clear-linux-documentation#799]
There are directions to create a new autospec package, but we don't have docs on how to update an existing package (or how to send the [PATCH] to the mailing list to get it updated)

**Comment by puneetse** [comment]
I transferred this request to our docs repo for better tracking.

For how to submit a patch, see https://github.com/clearlinux/distribution/blob/master/contributing.md and let us know if anything can be improved.

If the autospec documentation doesn't link to this already, we should consider it.

**Comment by mvincerx** [comment]
I'll add an example on how to update an existing package in our [autospec guide](https://docs.01.org/clearlinux/latest/guides/clear/autospec.html).

**Comment by mvincerx** [comment]
Closed per release of GH-827.
