### ISSUE TITLE
Minimum system requirements SSE 4.1 or SSE 4.2 ?

### ISSUE THREAD

**Issue by VadymVolos** [clearlinux/clear-linux-documentation#809]
Hi! 

Please correct the minimum requirements:
https://docs.01.org/clearlinux/latest/reference/system-requirements.html

The article says:
> Clear Linux OS requires an x86 64-bit processor which supports Intel® Streaming SIMD Extensions 4.1 (Intel® SSE 4.1), and it requires a system that supports UEFI.

But during installation I get an error:
> [ FAIL ] FATAL : Detected Missing Required CPU Feature: Streaming SIMD Extensions v4.2 (sse4_2)

https://github.com/clearlinux/distribution/issues/364#issuecomment-532985800

---
![2019-09-19](https://user-images.githubusercontent.com/12669290/65221522-dd6f9280-dac5-11e9-8e44-64a26cddfe21.png)

**Comment by ahkok** [comment]
Moved to the documentation project. The requirement is SSE 4.2.

**Comment by ahkok** [comment]
Note: I'm 100% sure you can configure virtualbox to enable this, but it may depend on whether your host CPU supports it.

**Comment by VadymVolos** [comment]
> but it may depend on whether your host CPU supports it.

No, my CPU only SSE 4.1.

**Comment by ahkok** [comment]
Right. Unfortunately then you're stuck with full emulation only. Thanks for filing the bug against our incorrect documentation, though.
