### ISSUE TITLE
Simplify language

### ISSUE THREAD

**Issue by krisdale** [clearlinux/clear-linux-documentation#858]
**Simplify language**
Find sentences or wording in existing documentation that can be simplified and simplify them.

Refer to the Contribution guide for additional info regarding language and style. 
https://docs.01.org/clearlinux/latest/collaboration/collaboration.html

**Comment by cjwilburn** [comment]
May I take this one?

**Comment by mvincerx** [comment]
You bet. If you want to simplify language in multiple docs, I recommend creating a new branch for each doc. As long as the editing adds value, you're good to go. See our [contributing guide](https://docs.01.org/clearlinux/latest/collaboration/collaboration.html#contribute-via-github).

**Comment by mvincerx** [comment]
Hi @cjwilburn, if you'd like to take this for Hacktoberfest, please do so before midnight tonight. 
We'd love to have your contributions.

**Comment by mvincerx** [comment]
Closed because Hacktoberfest ended on 10-31-2019.
FYI: @cjwilburn Feel free to contribute to our docs anytime.
