### ISSUE TITLE
Please add the guide to run Clear Linux image on Digital Ocean

### ISSUE THREAD

**Issue by igor-petruk** [clearlinux/clear-linux-documentation#886]
**Do you think Clear Linux documentation needs a new document? Please describe.**
Developer; System Administrator; or Basic User.

**Should the new document be a guide, a reference, or a tutorial?**
Getting Started -> Deploy ot the cloud

**Describe or provide examples of similar documents, if possible, from other web sites**
https://docs.01.org/clearlinux/latest/get-started/cloud-install/gce.html

**Additional context**
Straightforward download of the Cloud Guest Image and running it as Custom Image (for Open Container) on Digital Ocean does not boot. Not sure if there is something to be fixed or something the user should do

**Comment by mvincerx** [comment]
@bktan8 will start this week.

**Comment by mvincerx** [comment]
Waiting on the correct image.
