### ISSUE TITLE
PHP tutorial documentation section is missing nesting or incorrectly nested

### ISSUE THREAD

**Issue by JSEHV** [clearlinux/clear-linux-documentation#888]
The PHP tutorial documentation on https://docs.01.org/clearlinux/latest/tutorials/index.html is missing nesting or not nested correctly, as the other tutorials. Every chapter is shown as a separate tutorial between OpenVINO and Proxy configuration.

**Comment by mvincerx** [comment]
Good catch, @JSEHV.  @MCamp859.   The PHP tutorial has a few formatting errors.  Will you please apply correct alignment of items below the `.. contents::` directive? This is the reason that the left-side menu does not show correct "nesting," as @JSEHV points out.  Please fix all formatting errors and apply your magic too. Thanks
