### ISSUE TITLE
Typo in Chinese mixer.html

### ISSUE THREAD

**Issue by pixelgeek** [clearlinux/clear-linux-documentation#889]
In file https://docs.01.org/clearlinux/latest/zh_CN/guides/clear/mixer.html

在 mix 中再次列出 buddles 以确认移除。

should read

在 mix 中再次列出 bundles 以确认移除。

**Comment by intelkevinputnam** [comment]
Addressed with PR: https://github.com/clearlinux/clear-linux-documentation-zh-CN/pull/1

**Comment by intelkevinputnam** [comment]
Published just now, so the fix is in.

**Comment by mvincerx** [comment]
Thank you for closing the loop.
