### ISSUE TITLE
Review Kubernetes/Kata documentation

### ISSUE THREAD

**Issue by puneetse** [clearlinux/clear-linux-documentation#894]
**Describe the error/improvement to an existing document or image**
Overtime the Kubernetes documentation has become more complex. I recently had to do a deployment and found the documentation tough to follow through. 

Additionally, I've noticed key steps that were once in the documentation have somehow been lost over time. For example, the note about cni-plugins: https://github.com/clearlinux/clear-linux-documentation/pull/393

I would like to see more information about how to disable kata-runtime as a default runtime too.

**Additional context**
https://docs.01.org/clearlinux/latest/tutorials/kubernetes.html

**Comment by mvincerx** [comment]
Work with @mythi and @eadamsintel.  Need to publish by asap.

**Comment by eadamsintel** [comment]
@puneetse  The CNI plugins section is actually the "Install Pod Network add-on" section and there is a link to the kubernetes documentation on how to do that. I've tried several in the past without issue.  https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/create-cluster-kubeadm/#pod-network  

I think though that crio is still setup by default when you install and initialize cloud-native-basic.  I also think the `manage_network_ns_lifecycle = true` is set by default as well in the crio.conf.  I think the bigger question is should crio be the default or should containerd be the default.  It would be worthwhile to describe how to setup containerd but then this section starts to get complex.

As far as disabling Kata from what I can tell Kata is not setup as the default runtime in these instructions.  In the past when you initialized cloud-native-basic it setup the /etc/crio/crio.conf file automatically and added in the Kata runtimes.  When you add in the kata runtime class handler it allows you to schedule Pods as kata containers when they specify to use the kata-runtime.  It would be worthwhile to link to [Run a Kubernetes pod with Kata](https://github.com/kata-containers/documentation/blob/c017e2519d8b0ff0004f5e42efb95be8c2a0743f/how-to/run-kata-with-k8s.md#run-a-kubernetes-pod-with-kata-containers)   The current behavior should be verified though.  Perhaps just adding a note that Kata is not the default runtime in this setup would help clarify things. I don't believe that it is. It never was setup that way in the recent past.   That link above also describes how to enable with containerd and crio.  I think linking to this might be better than actually writing out a contianerd section.

**Comment by puneetse** [comment]
Thanks @eadamsintel. I have been making edits as I've been going along and will open a PR we can discuss around. 

> @puneetse The CNI plugins section is actually the "Install Pod Network add-on"

The problem is that CL distributes CNI plugins under `/usr/libexec/` and CRI expects them udner `/opt/cni/bin`, which CL doesn't distribute content under. This may not be a problem for Flannel but it is for NodePort, for example. 

https://kubernetes.io/docs/concepts/extend-kubernetes/compute-storage-net/network-plugins/

I think you can either symlink them (as was documented previously) or start kubelet with a `cni-bin-dir` parameter.

> As far as disabling Kata from what I can tell Kata is not setup as the default runtime in these instructions.

It's true CRI+O isn't configured to unless you follow the step, but Docker is. 

The `cloud-native-basic` bundle includes `kata-runtime`. Docker in CL is set to use `kata-runtime` as the default runtime if it is present. Therefore if you're using the Dockershim instead of CRI+O the control plane pods are started with `kata-runtime`.

**Comment by mythi** [comment]
> For example, the note about cni-plugins: #393

CRI-O in Clear Linux is configured to use both `/opt/cni/bin` and `/usr/libexec/cni`

**Comment by mythi** [comment]
> Docker in CL is set to use kata-runtime as the default runtime if it is present.

We've kept Docker out of the kubernetes doc on purpose. Also, the bundles are so that docker is not pulled in but containerd/cri-o as the CRI implementations.

It is true that Docker is set as the default runtime for docker if kvm is present. Before changing any docs, we should have the conversation do we still want to keep the setting like that. See: https://github.com/clearlinux/distribution/issues/1127#issuecomment-530033428

**Comment by puneetse** [comment]
> We've kept Docker out of the kubernetes doc on purpose. Also, the bundles are so that docker is not pulled in but containerd/cri-o as the CRI implementations.

If it's intended to not use Docker with Kubernetes, this should be explicitly stated or the steps provided to work with Docker because right now it is possible to enter this state with both bundles installed. 

Currently the document implicitly implies using CRI+O; I used Dockershim and ran into a combination of versions where the control plane pods didn't play nice with kata and was annoying to debug.

**Comment by eadamsintel** [comment]
I just looked at Ubuntu guides and  arch linux guides and neither go into details on crio or containerd.  Part of the reason this article is written this way is to show how to integrate with Kata containers.  The other articles don't cover crio or containerd which allows you to choose a runtime and I think just assume dockershim is used.   The kata team has switched back and forth between crio and containerd as a preferred runtime so there is no clear consensus on a best one to use so documenting both makes sense.  To me what makes sense to document the "Clear" way for setting up Kubernetes is to cover how to setup between the 3 CRI interfaces (dockershim, crio, containerd) and then link to other guides wherever possible.

**Comment by mythi** [comment]
It's fine to document both containerd and cri-o but docker should be left out (we can document the reasoning).

> setup between the 3 CRI interfaces (dockershim, crio, containerd)

There's no 3 CRI interfaces. dockershim uses containerd so it's just one extra layer on top.

Also, FYI distribution/issues/1451

**Comment by eadamsintel** [comment]
I commented on 1451. I agree that kata-runtime should not be the default.

**Comment by puneetse** [comment]
https://github.com/clearlinux/distribution/issues/1451

I'll hold on this under those changes are underway.

**Comment by mythi** [comment]
> I'll hold on this under those changes are underway.

Even with those changes, it still holds that either containerd or cri-o is preferred.

**Comment by mvincerx** [comment]
@puneetse will collab with @bd-dean.

**Comment by eadamsintel** [comment]
@mythi Is it expected that containerd will also find this `/usr/libexec/cni` directory? I was playing around trying to get a containerd kubernetes cluster up and running following mostly manual steps. It complained there were no plugins in /opt/cni. I installed the plugins following an external guide and got it to work. I've not played around with it anymore than that though.

**Comment by mythi** [comment]
The content in `/usr/libexec/cni` is needed by the container runtime if the CNI you're installing is not self-contained but depends on the "cni-plugins" package installed there (on Clear Linux). 

containerd can only be configured to look in one directory. Therefore, the workaround is to symlink `/usr/libexec/cni` to `/opt/cni/bin`. CRI-O is nice because any directory can be configured.

Kubernetes/CRI-O/Kata nicely comes out of the box today. Therefore, my preference is #917 would skip containerd and especially docker.

**Comment by puneetse** [comment]
@mythi can this be done in the kubelet service file by adding `--cni-bin-dir=/usr/libexec/cni`?https://kubernetes.io/docs/concepts/extend-kubernetes/compute-storage-net/network-plugins/

> Kubernetes/CRI-O/Kata nicely comes out of the box today. Therefore, my preference is #917 would skip containerd and especially docker.

There are people who will run across these other runtimes and try to use them (like I did). So we either need to document them with the necessary workarounds, or explicitly state in the documentation CRI+O is the only supported runtime to use on Clear Linux,

**Comment by mythi** [comment]
`--cni-bin-dir` is specific to dockershim and does not help with crio/containerd. 

> CRI+O is the only supported runtime to use on Clear Linux,

If only crio is used in validation, I'd say this statement is justified.

**Comment by mvincerx** [comment]
Closed per release of GH-1030.
