### ISSUE TITLE
Review for proper figure syntax.

### ISSUE THREAD

**Issue by puneetse** [clearlinux/clear-linux-documentation#896]
**Describe the error/improvement to an existing document or image**

I recently notice that some of our documentation is not using the correct syntax for caption-text in figures/images.

To render captions-text with the intended format and HTML code, the caption text needs to be indented under the figure block, like so:

```
   .. figure:: /_figures/aws/aws-web-1.png
      :scale: 50 %
      :alt: AWS Console

      Figure 1: :guilabel:`AWS Console`
```

I've seen (and made the mistake myself) of having the caption text outside of the figure block or in a separate paragraph, like so:
```
   .. figure:: figures/hyper-v/hyper-v-01.png
      :scale: 100%
      :alt: Hyper-V Manager from the Start menu

   Figure 1: Hyper-V Manager from the Start menu
```

Skimming through the docs I see at least a few pages like this so and overall review would be nice.

**Comment by mvincerx** [comment]
See Forum: https://community.clearlinux.org/t/help-us-correct-incorrect-figure-syntax-in-the-docs/2182

**Comment by mvincerx** [comment]
TCS will follow up on 12/16 in Docs meeting.
