### ISSUE TITLE
make venv doesn't work on Clear Linux OS

### ISSUE THREAD

**Issue by puneetse** [clearlinux/clear-linux-documentation#905]
`make venv` doesn't work on Clear Linux for me because `$(PY_VERSION)` isn't an environment variable out of the box

```
venv:
	virtualenv -p python$(PY_VERSION) venv;
	source venv/bin/activate; \
	pip3 install -r requirements.txt;
```

There are some other ways to determine python version, but I was able to use it without specifying a `-p` parameter at all.

> The default is the interpreter that virtualenv was installed with (/usr/bin/python3)

@mvincerx can you check if this is suitable for your systems too? Thanks for adding this make target. I found it useful.

**Comment by mvincerx** [comment]
Hey @puneetse. I should've let you know that I'm currently working on updating the README for this very purpose. It was on my back-burner list for a while to document it. I'll keep you posted.
