### ISSUE TITLE
Add CL Dissector Django app guide. 

### ISSUE THREAD

**Issue by mvincerx** [clearlinux/clear-linux-documentation#910]
**Do you think Clear Linux documentation needs a new document? Please describe.**
Create a guide showing the 3 main use cases for the  [Dissector](https://github.com/intel/clear-linux-dissector-web) app. Show general setup of app (git clone, etc.)

**Describe or provide examples of similar documents, if possible, from other web sites**
 Assure that use case of converting from Yocto to Clear Linux gives typical examples from standpoint of embedded developer. Have fun!

**Comment by mvincerx** [comment]
@krisdale meeting with brindle this week.

**Comment by krisdale** [comment]
PR in progress.

**Comment by mvincerx** [comment]
@krisdale @arbrindle. We're closing this for now. If in future, it's supported. Reopen this Issue.
