### ISSUE TITLE
Collaboration document link goes to a 404 page

### ISSUE THREAD

**Issue by eadamsintel** [clearlinux/clear-linux-documentation#915]
At the bottom of https://clearlinux.org/documentation there is a link to "Collaborate" which is https://docs.01.org/clearlinux/latest/reference/collaboration/collaboration.html  That link takes me to a 404 page whereas other https://docs.01.org links are valid.

**Comment by intelkevinputnam** [comment]
Thanks @eadamsintel. It should be an easy fix.

**Comment by intelkevinputnam** [comment]
I believe it's fixed. Can you take a look and close it if it is?

**Comment by eadamsintel** [comment]
Thanks for the quick fix.
