### ISSUE TITLE
Direct users to use LTS kernel in NVIDIA driver tutorial

### ISSUE THREAD

**Issue by lebensterben** [clearlinux/clear-linux-documentation#918]
Currently the documentation **mentioned** that LTS kernel is more likely to be compatible with the NVIDIA proprietary driver comparing to the frequently updated native kernel.

It'd be better if it would be rephrased to a tone that more strongly **suggests** and **directs** the user to use LTS kernel than just **mentioning** this fact.

For users, they're less likely to see graphical desktop environment failed to start because of some conflicts between the kernel and NVIDIA proprietary driver.

**Comment by puneetse** [comment]
In my experience the opposite can also be true pretty often: pairing against LTS kernels can result in breakages that have long since been fixed in newer version pairings. 

That is why I avoided being more direct with the language.

**Comment by mvincerx** [comment]
Hey @puneetse. Please let me know if you plan to address this or not. Thanks
https://docs.01.org/clearlinux/latest/tutorials/nvidia.html#install-dkms

**Comment by puneetse** [comment]
I'm not going to address this right now. We'll keep our ears open to datapoints coming in. If it starts to sway one way or the other, we can certainly revisit the issue.
