### ISSUE TITLE
Clear Linux* OS on Proxmox

### ISSUE THREAD

**Issue by JSEHV** [clearlinux/clear-linux-documentation#938]
As Proxmox is a very popular and well performing Virtual Environment, I would really like to see Proxmox added in the Get Started part under Install in a Virtual Machine.

**Do you think Clear Linux documentation needs a new document? Please describe.**
System Administrator

**Should the new document be a guide, a reference, or a tutorial?**
a Get Started

**Describe or provide examples of similar documents, if possible, from other web sites**
https://docs.01.org/clearlinux/latest/get-started/index.html#install-in-a-virtual-machine

**Additional context**
More info on Proxmox can be found on https://www.proxmox.com/en/proxmox-ve

**Comment by mvincerx** [comment]
@bktan8 will work on this.
