### ISSUE TITLE
Deploying Clear Linux on QingCloud

### ISSUE THREAD

**Issue by pixelgeek** [clearlinux/clear-linux-documentation#953]
Provide set up/ getting started guide for deploying Clear Linux on QingCloud

**Should the new document be a guide, a reference, or a tutorial?**
Recommend a type of document, based on the structure here: https://clearlinux.org/documentation/clear-linux

Getting started/Deploy to Cloud

**Describe or provide examples of similar documents, if possible, from other web sites**
Please provide an example of similar documents if possible.
Similar to https://docs.01.org/clearlinux/latest/get-started/cloud-install/aws-web.html

**Comment by pixelgeek** [comment]
Yuntong is working on this

**Comment by mvincerx** [comment]
Closed per https://github.com/clearlinux/clear-linux-documentation/pull/971
