### ISSUE TITLE
instructions for adding multi-boot on existing clear linux install (windows, etc.)

### ISSUE THREAD

**Issue by wakamex** [clearlinux/clear-linux-documentation#967]
Possible need for a new use case, or revive workable old tutorial.

- **target audience**: basic user
- **use case**: install windows after clear linux (for whatever reason, don't judge me)
- **type of document**: tutorial
- **example of similar documents**:

- old discussion at [https://community.clearlinux.org/t/multi-boot-clear-linux-os/442](https://community.clearlinux.org/t/multi-boot-clear-linux-os/442) discussed the old method of installing windows after clear linux.
- links to the [previous tutorial](https://clearlinux.org/documentation/clear-linux/tutorials/multi-boot) that gave instructions for how to do this. it worked. that's what I used on my first installation.
- it has since been deleted as per issue #503 and I can't find it in the github revision history. there are also many dead links to it from all over previous issues and posts ([here](https://community.clearlinux.org/t/how-to-recover-grub-after-installing-clear-linux-os/391/9) and previous link)

**Comment by mvincerx** [comment]
Hi @wakamex. This use case is somewhat unusual, but we'll discuss it when our team returns after the holidays.  Thanks for your patience.

**Comment by wakamex** [comment]
all the old instructions are still here, and links between the pages all seem to be working

- https://web.archive.org/web/20190602071312/https://clearlinux.org/documentation/clear-linux/tutorials/multi-boot
- https://web.archive.org/web/20190602071346/https://clearlinux.org/documentation/clear-linux/tutorials/multi-boot/multi-boot-win
- https://web.archive.org/web/20190602071311/https://clearlinux.org/documentation/clear-linux/tutorials/multi-boot/multi-boot-restore-bl#multi-boot-restore-bl

**Comment by mvincerx** [comment]
Our team put a lot of work into making the clr-boot-manager work with multiple OSes. 
I assumed that you were already aware of these multi-boot scenarios (esp. Windows):
- https://docs.01.org/clearlinux/latest/tutorials/multi-boot/multi-boot.html

[Method 2 here](https://docs.01.org/clearlinux/latest/tutorials/multi-boot/dual-boot-win.html#method-2-add-another-hard-disk-to-your-system-where-you-install-cl) seems the most applicable to your use case.

**Comment by wakamex** [comment]
those multi-boot scenarios cover a lot of ground **except** for installing windows after clear linux, which was actually the **only** recommended optional available in tutorial form earlier.

using a combination of the current live tutorials (covering clear linux after windows) and the old archived tutorials I linked (covering windows after clear linux) I managed to navigate the latter process quite easily, with the help of `clr-boot-manager` (which was strangely enough not recommended in the old "Restore the Clear Linux* OS boot loader" tutorial, in favour of `systemd-boot`).

**Comment by mvincerx** [comment]
@wakamex. An engineer is reviewing your request and working on a solution. Thanks for your patience.
