### ISSUE TITLE
Validating Clear Linux documentation not working

### ISSUE THREAD

**Issue by wisdomlight** [clearlinux/clear-linux-documentation#974]
This link https://clearlinux.org/downloads
Resuts in this page https://clearlinux.org/documentation/clear-linux/guides/maintenance/validate-signatures

I would appreciate advice on how to validate my Clear Linux download
Thank you

**Comment by mvincerx** [comment]
Here's a link to verify the integrity of the image: https://docs.01.org/clearlinux/latest/guides/maintenance/download-verify-decompress.html#verify-linux. Also, you may want to browse [this section for more general help with getting started](https://docs.01.org/clearlinux/latest/get-started/index.html). 

The above link that you sent, to "validate signatures" was likely found via a Google search. Will you please confirm how you discovered this link? 
I will file an issue to assure that a redirect is made to the proper page. Note that in some cases it may take Google a while to "forget" older pages in search results.

**Comment by krisdale** [comment]
Broken links on the clearlinux.org/downloads page have been resolved (as well as a broken link found on the developer page: https://clearlinux.org/developer)

**Comment by mvincerx** [comment]
@krisdale Thanks for your quick work on this.
