### ISSUE TITLE
Suggest users to use `balenaEtcher` in `Create a bootable USB drive`

### ISSUE THREAD

**Issue by lebensterben** [clearlinux/clear-linux-documentation#989]
[balenaEtcher](https://www.balena.io/etcher/) is an open-source software licensed under Apache License 2.0. Here are a few reasons to recommend using it:

First it's cross-platformed. There are ready to use images for macOS, Windows, and Linux. So we just need one working documentation and that would apply to users from all three major operating systems.

Second it has GUI interface and doesn't require manual configuration. Except from that being more friendly to many users, there are two major problems I encountered a while ago when I followed the tutorial to burn a usb image on macOS.
    1. `dd` command on macOS comes from BSD and has some trivial differences in syntax. I'm not sure whether it's still the case, but the command in the tutorial I saw doesn't work correctly.
    2. For large USB drives, setting an appropriate buffer size is crucial, or otherwise `dd` would fail. I'm not sure whether this only happens to macOS `dd`, but tinkering with buffer size is not fun. `balenaEther` doesn't require setting buffer size manually.

Third, it's simply faster than `dd`.

**Comment by mvincerx** [comment]
@lebensterben, Thanks for submitting this. We recently discussed using balenaEtcher--just last week. Our team will discuss this internally and get back to you. FYI @odwdinc @puneetse

**Comment by mvincerx** [comment]
@odwdinc Please submit a PR. Thanks

**Comment by odwdinc** [comment]
PR is drafted
https://github.com/clearlinux/clear-linux-documentation/pull/1021

**Comment by mvincerx** [comment]
@odwdinc. Sphinx tabs examples in raw format: 
- https://raw.githubusercontent.com/clearlinux/clear-linux-documentation/master/source/guides/stacks/dbrs.rst
- https://raw.githubusercontent.com/clearlinux/clear-linux-documentation/master/source/guides/maintenance/developer-workstation.rst

**Comment by mvincerx** [comment]
Published last week: https://docs.01.org/clearlinux/latest/get-started/bootable-usb.html#bootable-usb
Closing this issue.
