### ISSUE TITLE
Broken links in "Hosting Containers"

### ISSUE THREAD

**Issue by namm2** [clearlinux/clear-linux-documentation#998]
**Describe the error/improvement to an existing document or image**
Broken links in Hosting Containers: https://clearlinux.org/downloads/containers where they resulted in 404 error.

**Comment by mvincerx** [comment]
Good catch, @namm2. Thanks. I'm on this.

**Comment by mvincerx** [comment]
URLs are corrected now.  Please consider [contributing to our docs](https://docs.01.org/clearlinux/latest/collaboration/collaboration.html). We're an open source project.  Closing.
